// !!! WARNING !!! THIS FILE WAS AUTOGENERATED !!! DO NOT MODIFY !!!
// !!! WARNING !!! MODIFY INSTEAD: Definitions/ARM.json

#include "DebugServer2/Architecture/ARM/RegistersDescriptors.h"

using ds2::Architecture::FlagDef;
using ds2::Architecture::FlagSet;
using ds2::Architecture::GDBFeature;
using ds2::Architecture::GDBFeatureEntry;
using ds2::Architecture::GDBVectorDef;
using ds2::Architecture::GDBVectorUnion;
using ds2::Architecture::GDBVectorUnionField;
using ds2::Architecture::LLDBRegisterSet;
using ds2::Architecture::RegisterDef;

#if defined(ENDIAN_BIG)
#define REG_REL_OFFSET(MAXBYTES, RELOFF, REGSIZE) ((MAXBYTES) - ((RELOFF) + (REGSIZE))
#else
#define REG_REL_OFFSET(MAXBYTES, RELOFF, REGSIZE) (RELOFF)
#endif

namespace {

//
// Register Definitions (Forward Declarations)
//

// Register Set (cpsr)
extern RegisterDef const reg_def_cpsr;

// Register Set (fpscr)
extern RegisterDef const reg_def_fpscr;

// Register Set (gpr)
extern RegisterDef const reg_def_r0;
extern RegisterDef const reg_def_r1;
extern RegisterDef const reg_def_r2;
extern RegisterDef const reg_def_r3;
extern RegisterDef const reg_def_r4;
extern RegisterDef const reg_def_r5;
extern RegisterDef const reg_def_r6;
extern RegisterDef const reg_def_r7;
extern RegisterDef const reg_def_r8;
extern RegisterDef const reg_def_r9;
extern RegisterDef const reg_def_r10;
extern RegisterDef const reg_def_r11;
extern RegisterDef const reg_def_r12;
extern RegisterDef const reg_def_r13;
extern RegisterDef const reg_def_r14;
extern RegisterDef const reg_def_r15;

// Register Set (vfp-double)
extern RegisterDef const reg_def_d0;
extern RegisterDef const reg_def_d1;
extern RegisterDef const reg_def_d2;
extern RegisterDef const reg_def_d3;
extern RegisterDef const reg_def_d4;
extern RegisterDef const reg_def_d5;
extern RegisterDef const reg_def_d6;
extern RegisterDef const reg_def_d7;
extern RegisterDef const reg_def_d8;
extern RegisterDef const reg_def_d9;
extern RegisterDef const reg_def_d10;
extern RegisterDef const reg_def_d11;
extern RegisterDef const reg_def_d12;
extern RegisterDef const reg_def_d13;
extern RegisterDef const reg_def_d14;
extern RegisterDef const reg_def_d15;
extern RegisterDef const reg_def_d16;
extern RegisterDef const reg_def_d17;
extern RegisterDef const reg_def_d18;
extern RegisterDef const reg_def_d19;
extern RegisterDef const reg_def_d20;
extern RegisterDef const reg_def_d21;
extern RegisterDef const reg_def_d22;
extern RegisterDef const reg_def_d23;
extern RegisterDef const reg_def_d24;
extern RegisterDef const reg_def_d25;
extern RegisterDef const reg_def_d26;
extern RegisterDef const reg_def_d27;
extern RegisterDef const reg_def_d28;
extern RegisterDef const reg_def_d29;
extern RegisterDef const reg_def_d30;
extern RegisterDef const reg_def_d31;

// Register Set (vfp-quad)
extern RegisterDef const reg_def_q0;
extern RegisterDef const reg_def_q1;
extern RegisterDef const reg_def_q2;
extern RegisterDef const reg_def_q3;
extern RegisterDef const reg_def_q4;
extern RegisterDef const reg_def_q5;
extern RegisterDef const reg_def_q6;
extern RegisterDef const reg_def_q7;
extern RegisterDef const reg_def_q8;
extern RegisterDef const reg_def_q9;
extern RegisterDef const reg_def_q10;
extern RegisterDef const reg_def_q11;
extern RegisterDef const reg_def_q12;
extern RegisterDef const reg_def_q13;
extern RegisterDef const reg_def_q14;
extern RegisterDef const reg_def_q15;

// Register Set (vfp-single)
extern RegisterDef const reg_def_s0;
extern RegisterDef const reg_def_s1;
extern RegisterDef const reg_def_s2;
extern RegisterDef const reg_def_s3;
extern RegisterDef const reg_def_s4;
extern RegisterDef const reg_def_s5;
extern RegisterDef const reg_def_s6;
extern RegisterDef const reg_def_s7;
extern RegisterDef const reg_def_s8;
extern RegisterDef const reg_def_s9;
extern RegisterDef const reg_def_s10;
extern RegisterDef const reg_def_s11;
extern RegisterDef const reg_def_s12;
extern RegisterDef const reg_def_s13;
extern RegisterDef const reg_def_s14;
extern RegisterDef const reg_def_s15;
extern RegisterDef const reg_def_s16;
extern RegisterDef const reg_def_s17;
extern RegisterDef const reg_def_s18;
extern RegisterDef const reg_def_s19;
extern RegisterDef const reg_def_s20;
extern RegisterDef const reg_def_s21;
extern RegisterDef const reg_def_s22;
extern RegisterDef const reg_def_s23;
extern RegisterDef const reg_def_s24;
extern RegisterDef const reg_def_s25;
extern RegisterDef const reg_def_s26;
extern RegisterDef const reg_def_s27;
extern RegisterDef const reg_def_s28;
extern RegisterDef const reg_def_s29;
extern RegisterDef const reg_def_s30;
extern RegisterDef const reg_def_s31;

//
// LLDB Register Sets
//

// LLDB Register Set (General Purpose Registers)

RegisterDef const *const lldb_reg_defs_0[] = {
    &reg_def_r0,  &reg_def_r1,   &reg_def_r2,  &reg_def_r3,  &reg_def_r4,
    &reg_def_r5,  &reg_def_r6,   &reg_def_r7,  &reg_def_r8,  &reg_def_r9,
    &reg_def_r10, &reg_def_r11,  &reg_def_r12, &reg_def_r13, &reg_def_r14,
    &reg_def_r15, &reg_def_cpsr, nullptr};

LLDBRegisterSet const lldb_reg_set_0 = {"General Purpose Registers", 17,
                                        lldb_reg_defs_0};

// LLDB Register Set (VFP Registers)

RegisterDef const *const lldb_reg_defs_1[] = {
    &reg_def_s0,    &reg_def_s1,  &reg_def_s2,  &reg_def_s3,  &reg_def_s4,
    &reg_def_s5,    &reg_def_s6,  &reg_def_s7,  &reg_def_s8,  &reg_def_s9,
    &reg_def_s10,   &reg_def_s11, &reg_def_s12, &reg_def_s13, &reg_def_s14,
    &reg_def_s15,   &reg_def_s16, &reg_def_s17, &reg_def_s18, &reg_def_s19,
    &reg_def_s20,   &reg_def_s21, &reg_def_s22, &reg_def_s23, &reg_def_s24,
    &reg_def_s25,   &reg_def_s26, &reg_def_s27, &reg_def_s28, &reg_def_s29,
    &reg_def_s30,   &reg_def_s31, &reg_def_d0,  &reg_def_d1,  &reg_def_d2,
    &reg_def_d3,    &reg_def_d4,  &reg_def_d5,  &reg_def_d6,  &reg_def_d7,
    &reg_def_d8,    &reg_def_d9,  &reg_def_d10, &reg_def_d11, &reg_def_d12,
    &reg_def_d13,   &reg_def_d14, &reg_def_d15, &reg_def_d16, &reg_def_d17,
    &reg_def_d18,   &reg_def_d19, &reg_def_d20, &reg_def_d21, &reg_def_d22,
    &reg_def_d23,   &reg_def_d24, &reg_def_d25, &reg_def_d26, &reg_def_d27,
    &reg_def_d28,   &reg_def_d29, &reg_def_d30, &reg_def_d31, &reg_def_q0,
    &reg_def_q1,    &reg_def_q2,  &reg_def_q3,  &reg_def_q4,  &reg_def_q5,
    &reg_def_q6,    &reg_def_q7,  &reg_def_q8,  &reg_def_q9,  &reg_def_q10,
    &reg_def_q11,   &reg_def_q12, &reg_def_q13, &reg_def_q14, &reg_def_q15,
    &reg_def_fpscr, nullptr};

LLDBRegisterSet const lldb_reg_set_1 = {"VFP Registers", 81, lldb_reg_defs_1};

LLDBRegisterSet const *const lldb_reg_sets[] = {&lldb_reg_set_0,
                                                &lldb_reg_set_1, nullptr};

//
// GDB Features
//

// GDB Feature (org.gnu.gdb.arm.core)
GDBFeatureEntry const gdb_fents_org_gnu_gdb_arm_core[] = {
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r0},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r1},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r2},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r3},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r4},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r5},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r6},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r7},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r8},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r9},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r10},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r11},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r12},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r13},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r14},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r15},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_cpsr},
    {ds2::Architecture::kGDBFeatureTypeNone, nullptr}};
GDBFeature const gdb_feat_org_gnu_gdb_arm_core = {
    "org.gnu.gdb.arm.core", "arm-core.xml", 17, gdb_fents_org_gnu_gdb_arm_core};

// GDB Feature (org.gnu.gdb.arm.vfp)
GDBFeatureEntry const gdb_fents_org_gnu_gdb_arm_vfp[] = {
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d0},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d1},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d2},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d3},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d4},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d5},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d6},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d7},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d8},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d9},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d10},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d11},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d12},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d13},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d14},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d15},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d16},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d17},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d18},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d19},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d20},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d21},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d22},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d23},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d24},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d25},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d26},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d27},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d28},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d29},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d30},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_d31},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_fpscr},
    {ds2::Architecture::kGDBFeatureTypeNone, nullptr}};
GDBFeature const gdb_feat_org_gnu_gdb_arm_vfp = {
    "org.gnu.gdb.arm.vfp", "arm-vfpv3.xml", 33, gdb_fents_org_gnu_gdb_arm_vfp};

// GDB Feature (org.gnu.gdb.arm.neon)
GDBFeature const gdb_feat_org_gnu_gdb_arm_neon = {"org.gnu.gdb.arm.neon",
                                                  nullptr, 0, nullptr};

// GDB Features (all)
GDBFeature const *const gdb_features[] = {
    &gdb_feat_org_gnu_gdb_arm_core, &gdb_feat_org_gnu_gdb_arm_vfp,
    &gdb_feat_org_gnu_gdb_arm_neon, nullptr};

//
// LLDB Register Invalidation/Container Sets
//

RegisterDef const *const reg_inv_defs_cpsr[] = {
    &reg_def_r8,  &reg_def_r9,  &reg_def_r10, &reg_def_r11,
    &reg_def_r12, &reg_def_r13, &reg_def_r14, nullptr};
RegisterDef const *const reg_inv_defs_s0[] = {
    &reg_def_q0, &reg_def_d0, &reg_def_d1, &reg_def_s0,
    &reg_def_s1, &reg_def_s2, &reg_def_s3, nullptr};
RegisterDef const *const reg_cnt_defs_s0[] = {&reg_def_q0, nullptr};
RegisterDef const *const reg_inv_defs_s1[] = {
    &reg_def_q0, &reg_def_d0, &reg_def_d1, &reg_def_s0,
    &reg_def_s1, &reg_def_s2, &reg_def_s3, nullptr};
RegisterDef const *const reg_cnt_defs_s1[] = {&reg_def_q0, nullptr};
RegisterDef const *const reg_inv_defs_s2[] = {
    &reg_def_q0, &reg_def_d0, &reg_def_d1, &reg_def_s0,
    &reg_def_s1, &reg_def_s2, &reg_def_s3, nullptr};
RegisterDef const *const reg_cnt_defs_s2[] = {&reg_def_q0, nullptr};
RegisterDef const *const reg_inv_defs_s3[] = {
    &reg_def_q0, &reg_def_d0, &reg_def_d1, &reg_def_s0,
    &reg_def_s1, &reg_def_s2, &reg_def_s3, nullptr};
RegisterDef const *const reg_cnt_defs_s3[] = {&reg_def_q0, nullptr};
RegisterDef const *const reg_inv_defs_s4[] = {
    &reg_def_q1, &reg_def_d2, &reg_def_d3, &reg_def_s4,
    &reg_def_s5, &reg_def_s6, &reg_def_s7, nullptr};
RegisterDef const *const reg_cnt_defs_s4[] = {&reg_def_q1, nullptr};
RegisterDef const *const reg_inv_defs_s5[] = {
    &reg_def_q1, &reg_def_d2, &reg_def_d3, &reg_def_s4,
    &reg_def_s5, &reg_def_s6, &reg_def_s7, nullptr};
RegisterDef const *const reg_cnt_defs_s5[] = {&reg_def_q1, nullptr};
RegisterDef const *const reg_inv_defs_s6[] = {
    &reg_def_q1, &reg_def_d2, &reg_def_d3, &reg_def_s4,
    &reg_def_s5, &reg_def_s6, &reg_def_s7, nullptr};
RegisterDef const *const reg_cnt_defs_s6[] = {&reg_def_q1, nullptr};
RegisterDef const *const reg_inv_defs_s7[] = {
    &reg_def_q1, &reg_def_d2, &reg_def_d3, &reg_def_s4,
    &reg_def_s5, &reg_def_s6, &reg_def_s7, nullptr};
RegisterDef const *const reg_cnt_defs_s7[] = {&reg_def_q1, nullptr};
RegisterDef const *const reg_inv_defs_s8[] = {
    &reg_def_q2, &reg_def_d4,  &reg_def_d5,  &reg_def_s8,
    &reg_def_s9, &reg_def_s10, &reg_def_s11, nullptr};
RegisterDef const *const reg_cnt_defs_s8[] = {&reg_def_q2, nullptr};
RegisterDef const *const reg_inv_defs_s9[] = {
    &reg_def_q2, &reg_def_d4,  &reg_def_d5,  &reg_def_s8,
    &reg_def_s9, &reg_def_s10, &reg_def_s11, nullptr};
RegisterDef const *const reg_cnt_defs_s9[] = {&reg_def_q2, nullptr};
RegisterDef const *const reg_inv_defs_s10[] = {
    &reg_def_q2, &reg_def_d4,  &reg_def_d5,  &reg_def_s8,
    &reg_def_s9, &reg_def_s10, &reg_def_s11, nullptr};
RegisterDef const *const reg_cnt_defs_s10[] = {&reg_def_q2, nullptr};
RegisterDef const *const reg_inv_defs_s11[] = {
    &reg_def_q2, &reg_def_d4,  &reg_def_d5,  &reg_def_s8,
    &reg_def_s9, &reg_def_s10, &reg_def_s11, nullptr};
RegisterDef const *const reg_cnt_defs_s11[] = {&reg_def_q2, nullptr};
RegisterDef const *const reg_inv_defs_s12[] = {
    &reg_def_q3,  &reg_def_d6,  &reg_def_d7,  &reg_def_s12,
    &reg_def_s13, &reg_def_s14, &reg_def_s15, nullptr};
RegisterDef const *const reg_cnt_defs_s12[] = {&reg_def_q3, nullptr};
RegisterDef const *const reg_inv_defs_s13[] = {
    &reg_def_q3,  &reg_def_d6,  &reg_def_d7,  &reg_def_s12,
    &reg_def_s13, &reg_def_s14, &reg_def_s15, nullptr};
RegisterDef const *const reg_cnt_defs_s13[] = {&reg_def_q3, nullptr};
RegisterDef const *const reg_inv_defs_s14[] = {
    &reg_def_q3,  &reg_def_d6,  &reg_def_d7,  &reg_def_s12,
    &reg_def_s13, &reg_def_s14, &reg_def_s15, nullptr};
RegisterDef const *const reg_cnt_defs_s14[] = {&reg_def_q3, nullptr};
RegisterDef const *const reg_inv_defs_s15[] = {
    &reg_def_q3,  &reg_def_d6,  &reg_def_d7,  &reg_def_s12,
    &reg_def_s13, &reg_def_s14, &reg_def_s15, nullptr};
RegisterDef const *const reg_cnt_defs_s15[] = {&reg_def_q3, nullptr};
RegisterDef const *const reg_inv_defs_s16[] = {
    &reg_def_q4,  &reg_def_d8,  &reg_def_d9,  &reg_def_s16,
    &reg_def_s17, &reg_def_s18, &reg_def_s19, nullptr};
RegisterDef const *const reg_cnt_defs_s16[] = {&reg_def_q4, nullptr};
RegisterDef const *const reg_inv_defs_s17[] = {
    &reg_def_q4,  &reg_def_d8,  &reg_def_d9,  &reg_def_s16,
    &reg_def_s17, &reg_def_s18, &reg_def_s19, nullptr};
RegisterDef const *const reg_cnt_defs_s17[] = {&reg_def_q4, nullptr};
RegisterDef const *const reg_inv_defs_s18[] = {
    &reg_def_q4,  &reg_def_d8,  &reg_def_d9,  &reg_def_s16,
    &reg_def_s17, &reg_def_s18, &reg_def_s19, nullptr};
RegisterDef const *const reg_cnt_defs_s18[] = {&reg_def_q4, nullptr};
RegisterDef const *const reg_inv_defs_s19[] = {
    &reg_def_q4,  &reg_def_d8,  &reg_def_d9,  &reg_def_s16,
    &reg_def_s17, &reg_def_s18, &reg_def_s19, nullptr};
RegisterDef const *const reg_cnt_defs_s19[] = {&reg_def_q4, nullptr};
RegisterDef const *const reg_inv_defs_s20[] = {
    &reg_def_q5,  &reg_def_d10, &reg_def_d11, &reg_def_s20,
    &reg_def_s21, &reg_def_s22, &reg_def_s23, nullptr};
RegisterDef const *const reg_cnt_defs_s20[] = {&reg_def_q5, nullptr};
RegisterDef const *const reg_inv_defs_s21[] = {
    &reg_def_q5,  &reg_def_d10, &reg_def_d11, &reg_def_s20,
    &reg_def_s21, &reg_def_s22, &reg_def_s23, nullptr};
RegisterDef const *const reg_cnt_defs_s21[] = {&reg_def_q5, nullptr};
RegisterDef const *const reg_inv_defs_s22[] = {
    &reg_def_q5,  &reg_def_d10, &reg_def_d11, &reg_def_s20,
    &reg_def_s21, &reg_def_s22, &reg_def_s23, nullptr};
RegisterDef const *const reg_cnt_defs_s22[] = {&reg_def_q5, nullptr};
RegisterDef const *const reg_inv_defs_s23[] = {
    &reg_def_q5,  &reg_def_d10, &reg_def_d11, &reg_def_s20,
    &reg_def_s21, &reg_def_s22, &reg_def_s23, nullptr};
RegisterDef const *const reg_cnt_defs_s23[] = {&reg_def_q5, nullptr};
RegisterDef const *const reg_inv_defs_s24[] = {
    &reg_def_q6,  &reg_def_d12, &reg_def_d13, &reg_def_s24,
    &reg_def_s25, &reg_def_s26, &reg_def_s27, nullptr};
RegisterDef const *const reg_cnt_defs_s24[] = {&reg_def_q6, nullptr};
RegisterDef const *const reg_inv_defs_s25[] = {
    &reg_def_q6,  &reg_def_d12, &reg_def_d13, &reg_def_s24,
    &reg_def_s25, &reg_def_s26, &reg_def_s27, nullptr};
RegisterDef const *const reg_cnt_defs_s25[] = {&reg_def_q6, nullptr};
RegisterDef const *const reg_inv_defs_s26[] = {
    &reg_def_q6,  &reg_def_d12, &reg_def_d13, &reg_def_s24,
    &reg_def_s25, &reg_def_s26, &reg_def_s27, nullptr};
RegisterDef const *const reg_cnt_defs_s26[] = {&reg_def_q6, nullptr};
RegisterDef const *const reg_inv_defs_s27[] = {
    &reg_def_q6,  &reg_def_d12, &reg_def_d13, &reg_def_s24,
    &reg_def_s25, &reg_def_s26, &reg_def_s27, nullptr};
RegisterDef const *const reg_cnt_defs_s27[] = {&reg_def_q6, nullptr};
RegisterDef const *const reg_inv_defs_s28[] = {
    &reg_def_q7,  &reg_def_d14, &reg_def_d15, &reg_def_s28,
    &reg_def_s29, &reg_def_s30, &reg_def_s31, nullptr};
RegisterDef const *const reg_cnt_defs_s28[] = {&reg_def_q7, nullptr};
RegisterDef const *const reg_inv_defs_s29[] = {
    &reg_def_q7,  &reg_def_d14, &reg_def_d15, &reg_def_s28,
    &reg_def_s29, &reg_def_s30, &reg_def_s31, nullptr};
RegisterDef const *const reg_cnt_defs_s29[] = {&reg_def_q7, nullptr};
RegisterDef const *const reg_inv_defs_s30[] = {
    &reg_def_q7,  &reg_def_d14, &reg_def_d15, &reg_def_s28,
    &reg_def_s29, &reg_def_s30, &reg_def_s31, nullptr};
RegisterDef const *const reg_cnt_defs_s30[] = {&reg_def_q7, nullptr};
RegisterDef const *const reg_inv_defs_s31[] = {
    &reg_def_q7,  &reg_def_d14, &reg_def_d15, &reg_def_s28,
    &reg_def_s29, &reg_def_s30, &reg_def_s31, nullptr};
RegisterDef const *const reg_cnt_defs_s31[] = {&reg_def_q7, nullptr};
RegisterDef const *const reg_inv_defs_d0[] = {
    &reg_def_q0, &reg_def_d0, &reg_def_d1, &reg_def_s0,
    &reg_def_s1, &reg_def_s2, &reg_def_s3, nullptr};
RegisterDef const *const reg_cnt_defs_d0[] = {&reg_def_q0, nullptr};
RegisterDef const *const reg_inv_defs_d1[] = {
    &reg_def_q0, &reg_def_d0, &reg_def_d1, &reg_def_s0,
    &reg_def_s1, &reg_def_s2, &reg_def_s3, nullptr};
RegisterDef const *const reg_cnt_defs_d1[] = {&reg_def_q0, nullptr};
RegisterDef const *const reg_inv_defs_d2[] = {
    &reg_def_q1, &reg_def_d2, &reg_def_d3, &reg_def_s4,
    &reg_def_s5, &reg_def_s6, &reg_def_s7, nullptr};
RegisterDef const *const reg_cnt_defs_d2[] = {&reg_def_q1, nullptr};
RegisterDef const *const reg_inv_defs_d3[] = {
    &reg_def_q1, &reg_def_d2, &reg_def_d3, &reg_def_s4,
    &reg_def_s5, &reg_def_s6, &reg_def_s7, nullptr};
RegisterDef const *const reg_cnt_defs_d3[] = {&reg_def_q1, nullptr};
RegisterDef const *const reg_inv_defs_d4[] = {
    &reg_def_q2, &reg_def_d4,  &reg_def_d5,  &reg_def_s8,
    &reg_def_s9, &reg_def_s10, &reg_def_s11, nullptr};
RegisterDef const *const reg_cnt_defs_d4[] = {&reg_def_q2, nullptr};
RegisterDef const *const reg_inv_defs_d5[] = {
    &reg_def_q2, &reg_def_d4,  &reg_def_d5,  &reg_def_s8,
    &reg_def_s9, &reg_def_s10, &reg_def_s11, nullptr};
RegisterDef const *const reg_cnt_defs_d5[] = {&reg_def_q2, nullptr};
RegisterDef const *const reg_inv_defs_d6[] = {
    &reg_def_q3,  &reg_def_d6,  &reg_def_d7,  &reg_def_s12,
    &reg_def_s13, &reg_def_s14, &reg_def_s15, nullptr};
RegisterDef const *const reg_cnt_defs_d6[] = {&reg_def_q3, nullptr};
RegisterDef const *const reg_inv_defs_d7[] = {
    &reg_def_q3,  &reg_def_d6,  &reg_def_d7,  &reg_def_s12,
    &reg_def_s13, &reg_def_s14, &reg_def_s15, nullptr};
RegisterDef const *const reg_cnt_defs_d7[] = {&reg_def_q3, nullptr};
RegisterDef const *const reg_inv_defs_d8[] = {
    &reg_def_q4,  &reg_def_d8,  &reg_def_d9,  &reg_def_s16,
    &reg_def_s17, &reg_def_s18, &reg_def_s19, nullptr};
RegisterDef const *const reg_cnt_defs_d8[] = {&reg_def_q4, nullptr};
RegisterDef const *const reg_inv_defs_d9[] = {
    &reg_def_q4,  &reg_def_d8,  &reg_def_d9,  &reg_def_s16,
    &reg_def_s17, &reg_def_s18, &reg_def_s19, nullptr};
RegisterDef const *const reg_cnt_defs_d9[] = {&reg_def_q4, nullptr};
RegisterDef const *const reg_inv_defs_d10[] = {
    &reg_def_q5,  &reg_def_d10, &reg_def_d11, &reg_def_s20,
    &reg_def_s21, &reg_def_s22, &reg_def_s23, nullptr};
RegisterDef const *const reg_cnt_defs_d10[] = {&reg_def_q5, nullptr};
RegisterDef const *const reg_inv_defs_d11[] = {
    &reg_def_q5,  &reg_def_d10, &reg_def_d11, &reg_def_s20,
    &reg_def_s21, &reg_def_s22, &reg_def_s23, nullptr};
RegisterDef const *const reg_cnt_defs_d11[] = {&reg_def_q5, nullptr};
RegisterDef const *const reg_inv_defs_d12[] = {
    &reg_def_q6,  &reg_def_d12, &reg_def_d13, &reg_def_s24,
    &reg_def_s25, &reg_def_s26, &reg_def_s27, nullptr};
RegisterDef const *const reg_cnt_defs_d12[] = {&reg_def_q6, nullptr};
RegisterDef const *const reg_inv_defs_d13[] = {
    &reg_def_q6,  &reg_def_d12, &reg_def_d13, &reg_def_s24,
    &reg_def_s25, &reg_def_s26, &reg_def_s27, nullptr};
RegisterDef const *const reg_cnt_defs_d13[] = {&reg_def_q6, nullptr};
RegisterDef const *const reg_inv_defs_d14[] = {
    &reg_def_q7,  &reg_def_d14, &reg_def_d15, &reg_def_s28,
    &reg_def_s29, &reg_def_s30, &reg_def_s31, nullptr};
RegisterDef const *const reg_cnt_defs_d14[] = {&reg_def_q7, nullptr};
RegisterDef const *const reg_inv_defs_d15[] = {
    &reg_def_q7,  &reg_def_d14, &reg_def_d15, &reg_def_s28,
    &reg_def_s29, &reg_def_s30, &reg_def_s31, nullptr};
RegisterDef const *const reg_cnt_defs_d15[] = {&reg_def_q7, nullptr};
RegisterDef const *const reg_inv_defs_d16[] = {&reg_def_q8, &reg_def_d16,
                                               &reg_def_d17, nullptr};
RegisterDef const *const reg_cnt_defs_d16[] = {&reg_def_q8, nullptr};
RegisterDef const *const reg_inv_defs_d17[] = {&reg_def_q8, &reg_def_d16,
                                               &reg_def_d17, nullptr};
RegisterDef const *const reg_cnt_defs_d17[] = {&reg_def_q8, nullptr};
RegisterDef const *const reg_inv_defs_d18[] = {&reg_def_q9, &reg_def_d18,
                                               &reg_def_d19, nullptr};
RegisterDef const *const reg_cnt_defs_d18[] = {&reg_def_q9, nullptr};
RegisterDef const *const reg_inv_defs_d19[] = {&reg_def_q9, &reg_def_d18,
                                               &reg_def_d19, nullptr};
RegisterDef const *const reg_cnt_defs_d19[] = {&reg_def_q9, nullptr};
RegisterDef const *const reg_inv_defs_d20[] = {&reg_def_q10, &reg_def_d20,
                                               &reg_def_d21, nullptr};
RegisterDef const *const reg_cnt_defs_d20[] = {&reg_def_q10, nullptr};
RegisterDef const *const reg_inv_defs_d21[] = {&reg_def_q10, &reg_def_d20,
                                               &reg_def_d21, nullptr};
RegisterDef const *const reg_cnt_defs_d21[] = {&reg_def_q10, nullptr};
RegisterDef const *const reg_inv_defs_d22[] = {&reg_def_q11, &reg_def_d22,
                                               &reg_def_d23, nullptr};
RegisterDef const *const reg_cnt_defs_d22[] = {&reg_def_q11, nullptr};
RegisterDef const *const reg_inv_defs_d23[] = {&reg_def_q11, &reg_def_d22,
                                               &reg_def_d23, nullptr};
RegisterDef const *const reg_cnt_defs_d23[] = {&reg_def_q11, nullptr};
RegisterDef const *const reg_inv_defs_d24[] = {&reg_def_q12, &reg_def_d24,
                                               &reg_def_d25, nullptr};
RegisterDef const *const reg_cnt_defs_d24[] = {&reg_def_q12, nullptr};
RegisterDef const *const reg_inv_defs_d25[] = {&reg_def_q12, &reg_def_d24,
                                               &reg_def_d25, nullptr};
RegisterDef const *const reg_cnt_defs_d25[] = {&reg_def_q12, nullptr};
RegisterDef const *const reg_inv_defs_d26[] = {&reg_def_q13, &reg_def_d26,
                                               &reg_def_d27, nullptr};
RegisterDef const *const reg_cnt_defs_d26[] = {&reg_def_q13, nullptr};
RegisterDef const *const reg_inv_defs_d27[] = {&reg_def_q13, &reg_def_d26,
                                               &reg_def_d27, nullptr};
RegisterDef const *const reg_cnt_defs_d27[] = {&reg_def_q13, nullptr};
RegisterDef const *const reg_inv_defs_d28[] = {&reg_def_q14, &reg_def_d28,
                                               &reg_def_d29, nullptr};
RegisterDef const *const reg_cnt_defs_d28[] = {&reg_def_q14, nullptr};
RegisterDef const *const reg_inv_defs_d29[] = {&reg_def_q14, &reg_def_d28,
                                               &reg_def_d29, nullptr};
RegisterDef const *const reg_cnt_defs_d29[] = {&reg_def_q14, nullptr};
RegisterDef const *const reg_inv_defs_d30[] = {&reg_def_q15, &reg_def_d30,
                                               &reg_def_d31, nullptr};
RegisterDef const *const reg_cnt_defs_d30[] = {&reg_def_q15, nullptr};
RegisterDef const *const reg_inv_defs_d31[] = {&reg_def_q15, &reg_def_d30,
                                               &reg_def_d31, nullptr};
RegisterDef const *const reg_cnt_defs_d31[] = {&reg_def_q15, nullptr};
RegisterDef const *const reg_inv_defs_q0[] = {
    &reg_def_q0, &reg_def_d0, &reg_def_d1, &reg_def_s0,
    &reg_def_s1, &reg_def_s2, &reg_def_s3, nullptr};
RegisterDef const *const reg_inv_defs_q1[] = {
    &reg_def_q1, &reg_def_d2, &reg_def_d3, &reg_def_s4,
    &reg_def_s5, &reg_def_s6, &reg_def_s7, nullptr};
RegisterDef const *const reg_inv_defs_q2[] = {
    &reg_def_q2, &reg_def_d4,  &reg_def_d5,  &reg_def_s8,
    &reg_def_s9, &reg_def_s10, &reg_def_s11, nullptr};
RegisterDef const *const reg_inv_defs_q3[] = {
    &reg_def_q3,  &reg_def_d6,  &reg_def_d7,  &reg_def_s12,
    &reg_def_s13, &reg_def_s14, &reg_def_s15, nullptr};
RegisterDef const *const reg_inv_defs_q4[] = {
    &reg_def_q4,  &reg_def_d8,  &reg_def_d9,  &reg_def_s16,
    &reg_def_s17, &reg_def_s18, &reg_def_s19, nullptr};
RegisterDef const *const reg_inv_defs_q5[] = {
    &reg_def_q5,  &reg_def_d10, &reg_def_d11, &reg_def_s20,
    &reg_def_s21, &reg_def_s22, &reg_def_s23, nullptr};
RegisterDef const *const reg_inv_defs_q6[] = {
    &reg_def_q6,  &reg_def_d12, &reg_def_d13, &reg_def_s24,
    &reg_def_s25, &reg_def_s26, &reg_def_s27, nullptr};
RegisterDef const *const reg_inv_defs_q7[] = {
    &reg_def_q7,  &reg_def_d14, &reg_def_d15, &reg_def_s28,
    &reg_def_s29, &reg_def_s30, &reg_def_s31, nullptr};
RegisterDef const *const reg_inv_defs_q8[] = {&reg_def_q8, &reg_def_d16,
                                              &reg_def_d17, nullptr};
RegisterDef const *const reg_inv_defs_q9[] = {&reg_def_q9, &reg_def_d18,
                                              &reg_def_d19, nullptr};
RegisterDef const *const reg_inv_defs_q10[] = {&reg_def_q10, &reg_def_d20,
                                               &reg_def_d21, nullptr};
RegisterDef const *const reg_inv_defs_q11[] = {&reg_def_q11, &reg_def_d22,
                                               &reg_def_d23, nullptr};
RegisterDef const *const reg_inv_defs_q12[] = {&reg_def_q12, &reg_def_d24,
                                               &reg_def_d25, nullptr};
RegisterDef const *const reg_inv_defs_q13[] = {&reg_def_q13, &reg_def_d26,
                                               &reg_def_d27, nullptr};
RegisterDef const *const reg_inv_defs_q14[] = {&reg_def_q14, &reg_def_d28,
                                               &reg_def_d29, nullptr};
RegisterDef const *const reg_inv_defs_q15[] = {&reg_def_q15, &reg_def_d30,
                                               &reg_def_d31, nullptr};

//
// Register Definitions
//

RegisterDef const reg_def_r0 = {
    "r0",
    nullptr,
    "arg1",
    "arg1",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r0,
    ds2::Architecture::ARM::reg_gdb_r0,
    ds2::Architecture::ARM::reg_ehframe_r0,
    ds2::Architecture::ARM::reg_lldb_r0,
    0,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r1 = {
    "r1",
    nullptr,
    "arg2",
    "arg2",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r1,
    ds2::Architecture::ARM::reg_gdb_r1,
    ds2::Architecture::ARM::reg_ehframe_r1,
    ds2::Architecture::ARM::reg_lldb_r1,
    4,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r2 = {
    "r2",
    nullptr,
    "arg3",
    "arg3",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r2,
    ds2::Architecture::ARM::reg_gdb_r2,
    ds2::Architecture::ARM::reg_ehframe_r2,
    ds2::Architecture::ARM::reg_lldb_r2,
    8,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r3 = {
    "r3",
    nullptr,
    "arg4",
    "arg4",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r3,
    ds2::Architecture::ARM::reg_gdb_r3,
    ds2::Architecture::ARM::reg_ehframe_r3,
    ds2::Architecture::ARM::reg_lldb_r3,
    12,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r4 = {
    "r4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r4,
    ds2::Architecture::ARM::reg_gdb_r4,
    ds2::Architecture::ARM::reg_ehframe_r4,
    ds2::Architecture::ARM::reg_lldb_r4,
    16,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r5 = {
    "r5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r5,
    ds2::Architecture::ARM::reg_gdb_r5,
    ds2::Architecture::ARM::reg_ehframe_r5,
    ds2::Architecture::ARM::reg_lldb_r5,
    20,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r6 = {
    "r6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r6,
    ds2::Architecture::ARM::reg_gdb_r6,
    ds2::Architecture::ARM::reg_ehframe_r6,
    ds2::Architecture::ARM::reg_lldb_r6,
    24,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r7 = {
    "r7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r7,
    ds2::Architecture::ARM::reg_gdb_r7,
    ds2::Architecture::ARM::reg_ehframe_r7,
    ds2::Architecture::ARM::reg_lldb_r7,
    28,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r8 = {
    "r8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r8,
    ds2::Architecture::ARM::reg_gdb_r8,
    ds2::Architecture::ARM::reg_ehframe_r8,
    ds2::Architecture::ARM::reg_lldb_r8,
    32,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r9 = {
    "r9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r9,
    ds2::Architecture::ARM::reg_gdb_r9,
    ds2::Architecture::ARM::reg_ehframe_r9,
    ds2::Architecture::ARM::reg_lldb_r9,
    36,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r10 = {
    "r10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r10,
    ds2::Architecture::ARM::reg_gdb_r10,
    ds2::Architecture::ARM::reg_ehframe_r10,
    ds2::Architecture::ARM::reg_lldb_r10,
    40,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r11 = {
    "r11",
    nullptr,
    "fp",
    "fp",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r11,
    ds2::Architecture::ARM::reg_gdb_r11,
    ds2::Architecture::ARM::reg_ehframe_r11,
    ds2::Architecture::ARM::reg_lldb_r11,
    44,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r12 = {
    "r12",
    nullptr,
    "ip",
    "ip",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r12,
    ds2::Architecture::ARM::reg_gdb_r12,
    ds2::Architecture::ARM::reg_ehframe_r12,
    ds2::Architecture::ARM::reg_lldb_r12,
    48,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r13 = {
    "r13",
    nullptr,
    "sp",
    "sp",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r13,
    ds2::Architecture::ARM::reg_gdb_r13,
    ds2::Architecture::ARM::reg_ehframe_r13,
    ds2::Architecture::ARM::reg_lldb_r13,
    52,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingDataPointer, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r14 = {
    "r14",
    nullptr,
    "lr",
    "lr",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r14,
    ds2::Architecture::ARM::reg_gdb_r14,
    ds2::Architecture::ARM::reg_ehframe_r14,
    ds2::Architecture::ARM::reg_lldb_r14,
    56,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_r15 = {
    "r15",
    nullptr,
    "pc",
    "pc",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_r15,
    ds2::Architecture::ARM::reg_gdb_r15,
    ds2::Architecture::ARM::reg_ehframe_r15,
    ds2::Architecture::ARM::reg_lldb_r15,
    60,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingCodePointer, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_cpsr = {
    "cpsr",
    nullptr,
    "flags",
    "flags",
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_cpsr,
    ds2::Architecture::ARM::reg_gdb_cpsr,
    ds2::Architecture::ARM::reg_ehframe_cpsr,
    ds2::Architecture::ARM::reg_lldb_cpsr,
    64,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingInteger, nullptr},
    0,
    reg_inv_defs_cpsr,
    nullptr};
RegisterDef const reg_def_s0 = {
    "s0",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s0,
    ds2::Architecture::ARM::reg_gdb_s0,
    -1,
    ds2::Architecture::ARM::reg_lldb_s0,
    80 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s0,
    reg_cnt_defs_s0};
RegisterDef const reg_def_s1 = {
    "s1",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s1,
    ds2::Architecture::ARM::reg_gdb_s1,
    -1,
    ds2::Architecture::ARM::reg_lldb_s1,
    80 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s1,
    reg_cnt_defs_s1};
RegisterDef const reg_def_s2 = {
    "s2",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s2,
    ds2::Architecture::ARM::reg_gdb_s2,
    -1,
    ds2::Architecture::ARM::reg_lldb_s2,
    80 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s2,
    reg_cnt_defs_s2};
RegisterDef const reg_def_s3 = {
    "s3",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s3,
    ds2::Architecture::ARM::reg_gdb_s3,
    -1,
    ds2::Architecture::ARM::reg_lldb_s3,
    80 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s3,
    reg_cnt_defs_s3};
RegisterDef const reg_def_s4 = {
    "s4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s4,
    ds2::Architecture::ARM::reg_gdb_s4,
    -1,
    ds2::Architecture::ARM::reg_lldb_s4,
    96 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s4,
    reg_cnt_defs_s4};
RegisterDef const reg_def_s5 = {
    "s5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s5,
    ds2::Architecture::ARM::reg_gdb_s5,
    -1,
    ds2::Architecture::ARM::reg_lldb_s5,
    96 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s5,
    reg_cnt_defs_s5};
RegisterDef const reg_def_s6 = {
    "s6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s6,
    ds2::Architecture::ARM::reg_gdb_s6,
    -1,
    ds2::Architecture::ARM::reg_lldb_s6,
    96 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s6,
    reg_cnt_defs_s6};
RegisterDef const reg_def_s7 = {
    "s7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s7,
    ds2::Architecture::ARM::reg_gdb_s7,
    -1,
    ds2::Architecture::ARM::reg_lldb_s7,
    96 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s7,
    reg_cnt_defs_s7};
RegisterDef const reg_def_s8 = {
    "s8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s8,
    ds2::Architecture::ARM::reg_gdb_s8,
    -1,
    ds2::Architecture::ARM::reg_lldb_s8,
    112 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s8,
    reg_cnt_defs_s8};
RegisterDef const reg_def_s9 = {
    "s9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s9,
    ds2::Architecture::ARM::reg_gdb_s9,
    -1,
    ds2::Architecture::ARM::reg_lldb_s9,
    112 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s9,
    reg_cnt_defs_s9};
RegisterDef const reg_def_s10 = {
    "s10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s10,
    ds2::Architecture::ARM::reg_gdb_s10,
    -1,
    ds2::Architecture::ARM::reg_lldb_s10,
    112 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s10,
    reg_cnt_defs_s10};
RegisterDef const reg_def_s11 = {
    "s11",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s11,
    ds2::Architecture::ARM::reg_gdb_s11,
    -1,
    ds2::Architecture::ARM::reg_lldb_s11,
    112 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s11,
    reg_cnt_defs_s11};
RegisterDef const reg_def_s12 = {
    "s12",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s12,
    ds2::Architecture::ARM::reg_gdb_s12,
    -1,
    ds2::Architecture::ARM::reg_lldb_s12,
    128 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s12,
    reg_cnt_defs_s12};
RegisterDef const reg_def_s13 = {
    "s13",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s13,
    ds2::Architecture::ARM::reg_gdb_s13,
    -1,
    ds2::Architecture::ARM::reg_lldb_s13,
    128 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s13,
    reg_cnt_defs_s13};
RegisterDef const reg_def_s14 = {
    "s14",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s14,
    ds2::Architecture::ARM::reg_gdb_s14,
    -1,
    ds2::Architecture::ARM::reg_lldb_s14,
    128 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s14,
    reg_cnt_defs_s14};
RegisterDef const reg_def_s15 = {
    "s15",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s15,
    ds2::Architecture::ARM::reg_gdb_s15,
    -1,
    ds2::Architecture::ARM::reg_lldb_s15,
    128 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s15,
    reg_cnt_defs_s15};
RegisterDef const reg_def_s16 = {
    "s16",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s16,
    ds2::Architecture::ARM::reg_gdb_s16,
    -1,
    ds2::Architecture::ARM::reg_lldb_s16,
    144 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s16,
    reg_cnt_defs_s16};
RegisterDef const reg_def_s17 = {
    "s17",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s17,
    ds2::Architecture::ARM::reg_gdb_s17,
    -1,
    ds2::Architecture::ARM::reg_lldb_s17,
    144 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s17,
    reg_cnt_defs_s17};
RegisterDef const reg_def_s18 = {
    "s18",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s18,
    ds2::Architecture::ARM::reg_gdb_s18,
    -1,
    ds2::Architecture::ARM::reg_lldb_s18,
    144 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s18,
    reg_cnt_defs_s18};
RegisterDef const reg_def_s19 = {
    "s19",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s19,
    ds2::Architecture::ARM::reg_gdb_s19,
    -1,
    ds2::Architecture::ARM::reg_lldb_s19,
    144 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s19,
    reg_cnt_defs_s19};
RegisterDef const reg_def_s20 = {
    "s20",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s20,
    ds2::Architecture::ARM::reg_gdb_s20,
    -1,
    ds2::Architecture::ARM::reg_lldb_s20,
    160 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s20,
    reg_cnt_defs_s20};
RegisterDef const reg_def_s21 = {
    "s21",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s21,
    ds2::Architecture::ARM::reg_gdb_s21,
    -1,
    ds2::Architecture::ARM::reg_lldb_s21,
    160 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s21,
    reg_cnt_defs_s21};
RegisterDef const reg_def_s22 = {
    "s22",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s22,
    ds2::Architecture::ARM::reg_gdb_s22,
    -1,
    ds2::Architecture::ARM::reg_lldb_s22,
    160 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s22,
    reg_cnt_defs_s22};
RegisterDef const reg_def_s23 = {
    "s23",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s23,
    ds2::Architecture::ARM::reg_gdb_s23,
    -1,
    ds2::Architecture::ARM::reg_lldb_s23,
    160 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s23,
    reg_cnt_defs_s23};
RegisterDef const reg_def_s24 = {
    "s24",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s24,
    ds2::Architecture::ARM::reg_gdb_s24,
    -1,
    ds2::Architecture::ARM::reg_lldb_s24,
    176 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s24,
    reg_cnt_defs_s24};
RegisterDef const reg_def_s25 = {
    "s25",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s25,
    ds2::Architecture::ARM::reg_gdb_s25,
    -1,
    ds2::Architecture::ARM::reg_lldb_s25,
    176 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s25,
    reg_cnt_defs_s25};
RegisterDef const reg_def_s26 = {
    "s26",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s26,
    ds2::Architecture::ARM::reg_gdb_s26,
    -1,
    ds2::Architecture::ARM::reg_lldb_s26,
    176 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s26,
    reg_cnt_defs_s26};
RegisterDef const reg_def_s27 = {
    "s27",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s27,
    ds2::Architecture::ARM::reg_gdb_s27,
    -1,
    ds2::Architecture::ARM::reg_lldb_s27,
    176 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s27,
    reg_cnt_defs_s27};
RegisterDef const reg_def_s28 = {
    "s28",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s28,
    ds2::Architecture::ARM::reg_gdb_s28,
    -1,
    ds2::Architecture::ARM::reg_lldb_s28,
    192 + REG_REL_OFFSET(16, 0, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s28,
    reg_cnt_defs_s28};
RegisterDef const reg_def_s29 = {
    "s29",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s29,
    ds2::Architecture::ARM::reg_gdb_s29,
    -1,
    ds2::Architecture::ARM::reg_lldb_s29,
    192 + REG_REL_OFFSET(16, 4, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s29,
    reg_cnt_defs_s29};
RegisterDef const reg_def_s30 = {
    "s30",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s30,
    ds2::Architecture::ARM::reg_gdb_s30,
    -1,
    ds2::Architecture::ARM::reg_lldb_s30,
    192 + REG_REL_OFFSET(16, 8, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s30,
    reg_cnt_defs_s30};
RegisterDef const reg_def_s31 = {
    "s31",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM::reg_dwarf_s31,
    ds2::Architecture::ARM::reg_gdb_s31,
    -1,
    ds2::Architecture::ARM::reg_lldb_s31,
    192 + REG_REL_OFFSET(16, 12, 4),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEESingle,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEESingle, nullptr},
    0,
    reg_inv_defs_s31,
    reg_cnt_defs_s31};
RegisterDef const reg_def_d0 = {
    "d0",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d0,
    ds2::Architecture::ARM::reg_gdb_d0,
    -1,
    ds2::Architecture::ARM::reg_lldb_d0,
    80 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d0,
    reg_cnt_defs_d0};
RegisterDef const reg_def_d1 = {
    "d1",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d1,
    ds2::Architecture::ARM::reg_gdb_d1,
    -1,
    ds2::Architecture::ARM::reg_lldb_d1,
    80 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d1,
    reg_cnt_defs_d1};
RegisterDef const reg_def_d2 = {
    "d2",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d2,
    ds2::Architecture::ARM::reg_gdb_d2,
    -1,
    ds2::Architecture::ARM::reg_lldb_d2,
    96 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d2,
    reg_cnt_defs_d2};
RegisterDef const reg_def_d3 = {
    "d3",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d3,
    ds2::Architecture::ARM::reg_gdb_d3,
    -1,
    ds2::Architecture::ARM::reg_lldb_d3,
    96 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d3,
    reg_cnt_defs_d3};
RegisterDef const reg_def_d4 = {
    "d4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d4,
    ds2::Architecture::ARM::reg_gdb_d4,
    -1,
    ds2::Architecture::ARM::reg_lldb_d4,
    112 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d4,
    reg_cnt_defs_d4};
RegisterDef const reg_def_d5 = {
    "d5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d5,
    ds2::Architecture::ARM::reg_gdb_d5,
    -1,
    ds2::Architecture::ARM::reg_lldb_d5,
    112 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d5,
    reg_cnt_defs_d5};
RegisterDef const reg_def_d6 = {
    "d6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d6,
    ds2::Architecture::ARM::reg_gdb_d6,
    -1,
    ds2::Architecture::ARM::reg_lldb_d6,
    128 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d6,
    reg_cnt_defs_d6};
RegisterDef const reg_def_d7 = {
    "d7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d7,
    ds2::Architecture::ARM::reg_gdb_d7,
    -1,
    ds2::Architecture::ARM::reg_lldb_d7,
    128 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d7,
    reg_cnt_defs_d7};
RegisterDef const reg_def_d8 = {
    "d8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d8,
    ds2::Architecture::ARM::reg_gdb_d8,
    -1,
    ds2::Architecture::ARM::reg_lldb_d8,
    144 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d8,
    reg_cnt_defs_d8};
RegisterDef const reg_def_d9 = {
    "d9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d9,
    ds2::Architecture::ARM::reg_gdb_d9,
    -1,
    ds2::Architecture::ARM::reg_lldb_d9,
    144 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d9,
    reg_cnt_defs_d9};
RegisterDef const reg_def_d10 = {
    "d10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d10,
    ds2::Architecture::ARM::reg_gdb_d10,
    -1,
    ds2::Architecture::ARM::reg_lldb_d10,
    160 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d10,
    reg_cnt_defs_d10};
RegisterDef const reg_def_d11 = {
    "d11",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d11,
    ds2::Architecture::ARM::reg_gdb_d11,
    -1,
    ds2::Architecture::ARM::reg_lldb_d11,
    160 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d11,
    reg_cnt_defs_d11};
RegisterDef const reg_def_d12 = {
    "d12",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d12,
    ds2::Architecture::ARM::reg_gdb_d12,
    -1,
    ds2::Architecture::ARM::reg_lldb_d12,
    176 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d12,
    reg_cnt_defs_d12};
RegisterDef const reg_def_d13 = {
    "d13",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d13,
    ds2::Architecture::ARM::reg_gdb_d13,
    -1,
    ds2::Architecture::ARM::reg_lldb_d13,
    176 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d13,
    reg_cnt_defs_d13};
RegisterDef const reg_def_d14 = {
    "d14",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d14,
    ds2::Architecture::ARM::reg_gdb_d14,
    -1,
    ds2::Architecture::ARM::reg_lldb_d14,
    192 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d14,
    reg_cnt_defs_d14};
RegisterDef const reg_def_d15 = {
    "d15",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d15,
    ds2::Architecture::ARM::reg_gdb_d15,
    -1,
    ds2::Architecture::ARM::reg_lldb_d15,
    192 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d15,
    reg_cnt_defs_d15};
RegisterDef const reg_def_d16 = {
    "d16",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d16,
    ds2::Architecture::ARM::reg_gdb_d16,
    -1,
    ds2::Architecture::ARM::reg_lldb_d16,
    208 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d16,
    reg_cnt_defs_d16};
RegisterDef const reg_def_d17 = {
    "d17",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d17,
    ds2::Architecture::ARM::reg_gdb_d17,
    -1,
    ds2::Architecture::ARM::reg_lldb_d17,
    208 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d17,
    reg_cnt_defs_d17};
RegisterDef const reg_def_d18 = {
    "d18",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d18,
    ds2::Architecture::ARM::reg_gdb_d18,
    -1,
    ds2::Architecture::ARM::reg_lldb_d18,
    224 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d18,
    reg_cnt_defs_d18};
RegisterDef const reg_def_d19 = {
    "d19",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d19,
    ds2::Architecture::ARM::reg_gdb_d19,
    -1,
    ds2::Architecture::ARM::reg_lldb_d19,
    224 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d19,
    reg_cnt_defs_d19};
RegisterDef const reg_def_d20 = {
    "d20",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d20,
    ds2::Architecture::ARM::reg_gdb_d20,
    -1,
    ds2::Architecture::ARM::reg_lldb_d20,
    240 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d20,
    reg_cnt_defs_d20};
RegisterDef const reg_def_d21 = {
    "d21",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d21,
    ds2::Architecture::ARM::reg_gdb_d21,
    -1,
    ds2::Architecture::ARM::reg_lldb_d21,
    240 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d21,
    reg_cnt_defs_d21};
RegisterDef const reg_def_d22 = {
    "d22",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d22,
    ds2::Architecture::ARM::reg_gdb_d22,
    -1,
    ds2::Architecture::ARM::reg_lldb_d22,
    256 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d22,
    reg_cnt_defs_d22};
RegisterDef const reg_def_d23 = {
    "d23",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d23,
    ds2::Architecture::ARM::reg_gdb_d23,
    -1,
    ds2::Architecture::ARM::reg_lldb_d23,
    256 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d23,
    reg_cnt_defs_d23};
RegisterDef const reg_def_d24 = {
    "d24",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d24,
    ds2::Architecture::ARM::reg_gdb_d24,
    -1,
    ds2::Architecture::ARM::reg_lldb_d24,
    272 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d24,
    reg_cnt_defs_d24};
RegisterDef const reg_def_d25 = {
    "d25",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d25,
    ds2::Architecture::ARM::reg_gdb_d25,
    -1,
    ds2::Architecture::ARM::reg_lldb_d25,
    272 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d25,
    reg_cnt_defs_d25};
RegisterDef const reg_def_d26 = {
    "d26",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d26,
    ds2::Architecture::ARM::reg_gdb_d26,
    -1,
    ds2::Architecture::ARM::reg_lldb_d26,
    288 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d26,
    reg_cnt_defs_d26};
RegisterDef const reg_def_d27 = {
    "d27",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d27,
    ds2::Architecture::ARM::reg_gdb_d27,
    -1,
    ds2::Architecture::ARM::reg_lldb_d27,
    288 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d27,
    reg_cnt_defs_d27};
RegisterDef const reg_def_d28 = {
    "d28",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d28,
    ds2::Architecture::ARM::reg_gdb_d28,
    -1,
    ds2::Architecture::ARM::reg_lldb_d28,
    304 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d28,
    reg_cnt_defs_d28};
RegisterDef const reg_def_d29 = {
    "d29",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d29,
    ds2::Architecture::ARM::reg_gdb_d29,
    -1,
    ds2::Architecture::ARM::reg_lldb_d29,
    304 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d29,
    reg_cnt_defs_d29};
RegisterDef const reg_def_d30 = {
    "d30",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d30,
    ds2::Architecture::ARM::reg_gdb_d30,
    -1,
    ds2::Architecture::ARM::reg_lldb_d30,
    320 + REG_REL_OFFSET(16, 0, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d30,
    reg_cnt_defs_d30};
RegisterDef const reg_def_d31 = {
    "d31",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM::reg_dwarf_d31,
    ds2::Architecture::ARM::reg_gdb_d31,
    -1,
    ds2::Architecture::ARM::reg_lldb_d31,
    320 + REG_REL_OFFSET(16, 8, 8),
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEDouble,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingIEEEDouble, nullptr},
    0,
    reg_inv_defs_d31,
    reg_cnt_defs_d31};
RegisterDef const reg_def_q0 = {
    "q0",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q0,
    ds2::Architecture::ARM::reg_gdb_q0,
    -1,
    ds2::Architecture::ARM::reg_lldb_q0,
    80,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q0,
    nullptr};
RegisterDef const reg_def_q1 = {
    "q1",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q1,
    ds2::Architecture::ARM::reg_gdb_q1,
    -1,
    ds2::Architecture::ARM::reg_lldb_q1,
    96,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q1,
    nullptr};
RegisterDef const reg_def_q2 = {
    "q2",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q2,
    ds2::Architecture::ARM::reg_gdb_q2,
    -1,
    ds2::Architecture::ARM::reg_lldb_q2,
    112,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q2,
    nullptr};
RegisterDef const reg_def_q3 = {
    "q3",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q3,
    ds2::Architecture::ARM::reg_gdb_q3,
    -1,
    ds2::Architecture::ARM::reg_lldb_q3,
    128,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q3,
    nullptr};
RegisterDef const reg_def_q4 = {
    "q4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q4,
    ds2::Architecture::ARM::reg_gdb_q4,
    -1,
    ds2::Architecture::ARM::reg_lldb_q4,
    144,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q4,
    nullptr};
RegisterDef const reg_def_q5 = {
    "q5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q5,
    ds2::Architecture::ARM::reg_gdb_q5,
    -1,
    ds2::Architecture::ARM::reg_lldb_q5,
    160,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q5,
    nullptr};
RegisterDef const reg_def_q6 = {
    "q6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q6,
    ds2::Architecture::ARM::reg_gdb_q6,
    -1,
    ds2::Architecture::ARM::reg_lldb_q6,
    176,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q6,
    nullptr};
RegisterDef const reg_def_q7 = {
    "q7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q7,
    ds2::Architecture::ARM::reg_gdb_q7,
    -1,
    ds2::Architecture::ARM::reg_lldb_q7,
    192,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q7,
    nullptr};
RegisterDef const reg_def_q8 = {
    "q8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q8,
    ds2::Architecture::ARM::reg_gdb_q8,
    -1,
    ds2::Architecture::ARM::reg_lldb_q8,
    208,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q8,
    nullptr};
RegisterDef const reg_def_q9 = {
    "q9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q9,
    ds2::Architecture::ARM::reg_gdb_q9,
    -1,
    ds2::Architecture::ARM::reg_lldb_q9,
    224,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q9,
    nullptr};
RegisterDef const reg_def_q10 = {
    "q10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q10,
    ds2::Architecture::ARM::reg_gdb_q10,
    -1,
    ds2::Architecture::ARM::reg_lldb_q10,
    240,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q10,
    nullptr};
RegisterDef const reg_def_q11 = {
    "q11",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q11,
    ds2::Architecture::ARM::reg_gdb_q11,
    -1,
    ds2::Architecture::ARM::reg_lldb_q11,
    256,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q11,
    nullptr};
RegisterDef const reg_def_q12 = {
    "q12",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q12,
    ds2::Architecture::ARM::reg_gdb_q12,
    -1,
    ds2::Architecture::ARM::reg_lldb_q12,
    272,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q12,
    nullptr};
RegisterDef const reg_def_q13 = {
    "q13",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q13,
    ds2::Architecture::ARM::reg_gdb_q13,
    -1,
    ds2::Architecture::ARM::reg_lldb_q13,
    288,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q13,
    nullptr};
RegisterDef const reg_def_q14 = {
    "q14",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q14,
    ds2::Architecture::ARM::reg_gdb_q14,
    -1,
    ds2::Architecture::ARM::reg_lldb_q14,
    304,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q14,
    nullptr};
RegisterDef const reg_def_q15 = {
    "q15",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    128,
    ds2::Architecture::ARM::reg_dwarf_q15,
    ds2::Architecture::ARM::reg_gdb_q15,
    -1,
    ds2::Architecture::ARM::reg_lldb_q15,
    320,
    ds2::Architecture::kLLDBVectorFormatUInt8,
    ds2::Architecture::kEncodingIEEEExtended,
    ds2::Architecture::kFormatVector,
    {ds2::Architecture::kGDBEncodingUnknown, nullptr},
    0,
    reg_inv_defs_q15,
    nullptr};
RegisterDef const reg_def_fpscr = {
    "fpscr",
    nullptr,
    nullptr,
    nullptr,
    "float",
    32,
    -1,
    ds2::Architecture::ARM::reg_gdb_fpscr,
    -1,
    ds2::Architecture::ARM::reg_lldb_fpscr,
    336,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingInteger, nullptr},
    0,
    nullptr,
    nullptr};

} // namespace

//
// Public Definitions
//
namespace ds2 {
namespace Architecture {
namespace ARM {

LLDBDescriptor const LLDB = {2, lldb_reg_sets};
GDBDescriptor const GDB = {"arm", "GNU/Linux", 3, gdb_features};

} // namespace ARM
} // namespace Architecture
} // namespace ds2
