// !!! WARNING !!! THIS FILE WAS AUTOGENERATED !!! DO NOT MODIFY !!!
// !!! WARNING !!! MODIFY INSTEAD: ../../Definitions/arm64.json

#include "DebugServer2/Architecture/ARM64/RegistersDescriptors.h"

using ds2::Architecture::RegisterDef;
using ds2::Architecture::FlagDef;
using ds2::Architecture::FlagSet;
using ds2::Architecture::GDBVectorDef;
using ds2::Architecture::GDBVectorUnion;
using ds2::Architecture::GDBVectorUnionField;
using ds2::Architecture::GDBFeature;
using ds2::Architecture::GDBFeatureEntry;
using ds2::Architecture::LLDBRegisterSet;

#if defined(ENDIAN_BIG)
#define REG_REL_OFFSET(MAXBYTES, RELOFF, REGSIZE) ((MAXBYTES) - ((RELOFF) + (REGSIZE))
#else
#define REG_REL_OFFSET(MAXBYTES, RELOFF, REGSIZE) (RELOFF)
#endif

namespace {

//
// Register Definitions (Forward Declarations)
//

// Register Set (cpsr)
extern RegisterDef const reg_def_cpsr;

// Register Set (gpr)
extern RegisterDef const reg_def_r0;
extern RegisterDef const reg_def_r1;
extern RegisterDef const reg_def_r2;
extern RegisterDef const reg_def_r3;
extern RegisterDef const reg_def_r4;
extern RegisterDef const reg_def_r5;
extern RegisterDef const reg_def_r6;
extern RegisterDef const reg_def_r7;
extern RegisterDef const reg_def_r8;
extern RegisterDef const reg_def_r9;
extern RegisterDef const reg_def_r10;
extern RegisterDef const reg_def_r11;
extern RegisterDef const reg_def_r12;
extern RegisterDef const reg_def_r13;
extern RegisterDef const reg_def_r14;
extern RegisterDef const reg_def_r15;
extern RegisterDef const reg_def_r16;
extern RegisterDef const reg_def_r17;
extern RegisterDef const reg_def_r18;
extern RegisterDef const reg_def_r19;
extern RegisterDef const reg_def_r20;
extern RegisterDef const reg_def_r21;
extern RegisterDef const reg_def_r22;
extern RegisterDef const reg_def_r23;
extern RegisterDef const reg_def_r24;
extern RegisterDef const reg_def_r25;
extern RegisterDef const reg_def_r26;
extern RegisterDef const reg_def_r27;
extern RegisterDef const reg_def_r28;
extern RegisterDef const reg_def_r29;
extern RegisterDef const reg_def_r30;
extern RegisterDef const reg_def_r31;
extern RegisterDef const reg_def_pc;

// Register Set (pseudo-gpr32)
extern RegisterDef const reg_def_w0;
extern RegisterDef const reg_def_w1;
extern RegisterDef const reg_def_w2;
extern RegisterDef const reg_def_w3;
extern RegisterDef const reg_def_w4;
extern RegisterDef const reg_def_w5;
extern RegisterDef const reg_def_w6;
extern RegisterDef const reg_def_w7;
extern RegisterDef const reg_def_w8;
extern RegisterDef const reg_def_w9;
extern RegisterDef const reg_def_w10;
extern RegisterDef const reg_def_w11;
extern RegisterDef const reg_def_w12;
extern RegisterDef const reg_def_w13;
extern RegisterDef const reg_def_w14;
extern RegisterDef const reg_def_w15;
extern RegisterDef const reg_def_w16;
extern RegisterDef const reg_def_w17;
extern RegisterDef const reg_def_w18;
extern RegisterDef const reg_def_w19;
extern RegisterDef const reg_def_w20;
extern RegisterDef const reg_def_w21;
extern RegisterDef const reg_def_w22;
extern RegisterDef const reg_def_w23;
extern RegisterDef const reg_def_w24;
extern RegisterDef const reg_def_w25;
extern RegisterDef const reg_def_w26;
extern RegisterDef const reg_def_w27;
extern RegisterDef const reg_def_w28;
extern RegisterDef const reg_def_w29;
extern RegisterDef const reg_def_w30;

//
// LLDB Register Sets
//

// LLDB Register Set (General Purpose Registers)

RegisterDef const *const lldb_reg_defs_0[] = {
    &reg_def_r0,  &reg_def_r1,  &reg_def_r2,  &reg_def_r3,   &reg_def_r4,
    &reg_def_r5,  &reg_def_r6,  &reg_def_r7,  &reg_def_r8,   &reg_def_r9,
    &reg_def_r10, &reg_def_r11, &reg_def_r12, &reg_def_r13,  &reg_def_r14,
    &reg_def_r15, &reg_def_r16, &reg_def_r17, &reg_def_r18,  &reg_def_r19,
    &reg_def_r20, &reg_def_r21, &reg_def_r22, &reg_def_r23,  &reg_def_r24,
    &reg_def_r25, &reg_def_r26, &reg_def_r27, &reg_def_r28,  &reg_def_r29,
    &reg_def_r30, &reg_def_r31, &reg_def_pc,  &reg_def_cpsr, &reg_def_w0,
    &reg_def_w1,  &reg_def_w2,  &reg_def_w3,  &reg_def_w4,   &reg_def_w5,
    &reg_def_w6,  &reg_def_w7,  &reg_def_w8,  &reg_def_w9,   &reg_def_w10,
    &reg_def_w11, &reg_def_w12, &reg_def_w13, &reg_def_w14,  &reg_def_w15,
    &reg_def_w16, &reg_def_w17, &reg_def_w18, &reg_def_w19,  &reg_def_w20,
    &reg_def_w21, &reg_def_w22, &reg_def_w23, &reg_def_w24,  &reg_def_w25,
    &reg_def_w26, &reg_def_w27, &reg_def_w28, &reg_def_w29,  &reg_def_w30,
    nullptr};

LLDBRegisterSet const lldb_reg_set_0 = {"General Purpose Registers", 65,
                                        lldb_reg_defs_0};

LLDBRegisterSet const *const lldb_reg_sets[] = {&lldb_reg_set_0, nullptr};

//
// GDB Features
//

// GDB Feature (org.gnu.gdb.aarch64.core)
GDBFeatureEntry const gdb_fents_org_gnu_gdb_aarch64_core[] = {
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r0},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r1},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r2},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r3},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r4},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r5},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r6},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r7},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r8},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r9},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r10},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r11},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r12},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r13},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r14},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r15},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r16},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r17},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r18},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r19},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r20},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r21},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r22},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r23},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r24},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r25},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r26},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r27},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r28},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r29},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r30},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_r31},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_pc},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_cpsr},
    {ds2::Architecture::kGDBFeatureTypeNone, nullptr}};
GDBFeature const gdb_feat_org_gnu_gdb_aarch64_core = {
    "org.gnu.gdb.aarch64.core", "aarch64-core.xml", 34,
    gdb_fents_org_gnu_gdb_aarch64_core};

// GDB Features (all)
GDBFeature const *const gdb_features[] = {&gdb_feat_org_gnu_gdb_aarch64_core,
                                          nullptr};

//
// LLDB Register Invalidation/Container Sets
//

RegisterDef const *const reg_inv_defs_r0[] = {&reg_def_w0, nullptr};
RegisterDef const *const reg_inv_defs_r1[] = {&reg_def_w1, nullptr};
RegisterDef const *const reg_inv_defs_r2[] = {&reg_def_w2, nullptr};
RegisterDef const *const reg_inv_defs_r3[] = {&reg_def_w3, nullptr};
RegisterDef const *const reg_inv_defs_r4[] = {&reg_def_w4, nullptr};
RegisterDef const *const reg_inv_defs_r5[] = {&reg_def_w5, nullptr};
RegisterDef const *const reg_inv_defs_r6[] = {&reg_def_w6, nullptr};
RegisterDef const *const reg_inv_defs_r7[] = {&reg_def_w7, nullptr};
RegisterDef const *const reg_inv_defs_r8[] = {&reg_def_w8, nullptr};
RegisterDef const *const reg_inv_defs_r9[] = {&reg_def_w9, nullptr};
RegisterDef const *const reg_inv_defs_r10[] = {&reg_def_w10, nullptr};
RegisterDef const *const reg_inv_defs_r11[] = {&reg_def_w11, nullptr};
RegisterDef const *const reg_inv_defs_r12[] = {&reg_def_w12, nullptr};
RegisterDef const *const reg_inv_defs_r13[] = {&reg_def_w13, nullptr};
RegisterDef const *const reg_inv_defs_r14[] = {&reg_def_w14, nullptr};
RegisterDef const *const reg_inv_defs_r15[] = {&reg_def_w15, nullptr};
RegisterDef const *const reg_inv_defs_r16[] = {&reg_def_w16, nullptr};
RegisterDef const *const reg_inv_defs_r17[] = {&reg_def_w17, nullptr};
RegisterDef const *const reg_inv_defs_r18[] = {&reg_def_w18, nullptr};
RegisterDef const *const reg_inv_defs_r19[] = {&reg_def_w19, nullptr};
RegisterDef const *const reg_inv_defs_r20[] = {&reg_def_w20, nullptr};
RegisterDef const *const reg_inv_defs_r21[] = {&reg_def_w21, nullptr};
RegisterDef const *const reg_inv_defs_r22[] = {&reg_def_w22, nullptr};
RegisterDef const *const reg_inv_defs_r23[] = {&reg_def_w23, nullptr};
RegisterDef const *const reg_inv_defs_r24[] = {&reg_def_w24, nullptr};
RegisterDef const *const reg_inv_defs_r25[] = {&reg_def_w25, nullptr};
RegisterDef const *const reg_inv_defs_r26[] = {&reg_def_w26, nullptr};
RegisterDef const *const reg_inv_defs_r27[] = {&reg_def_w27, nullptr};
RegisterDef const *const reg_inv_defs_r28[] = {&reg_def_w28, nullptr};
RegisterDef const *const reg_inv_defs_r29[] = {&reg_def_w29, nullptr};
RegisterDef const *const reg_inv_defs_r30[] = {&reg_def_w30, nullptr};
RegisterDef const *const reg_inv_defs_w0[] = {&reg_def_r0, nullptr};
RegisterDef const *const reg_cnt_defs_w0[] = {&reg_def_r0, nullptr};
RegisterDef const *const reg_inv_defs_w1[] = {&reg_def_r1, nullptr};
RegisterDef const *const reg_cnt_defs_w1[] = {&reg_def_r1, nullptr};
RegisterDef const *const reg_inv_defs_w2[] = {&reg_def_r2, nullptr};
RegisterDef const *const reg_cnt_defs_w2[] = {&reg_def_r2, nullptr};
RegisterDef const *const reg_inv_defs_w3[] = {&reg_def_r3, nullptr};
RegisterDef const *const reg_cnt_defs_w3[] = {&reg_def_r3, nullptr};
RegisterDef const *const reg_inv_defs_w4[] = {&reg_def_r4, nullptr};
RegisterDef const *const reg_cnt_defs_w4[] = {&reg_def_r4, nullptr};
RegisterDef const *const reg_inv_defs_w5[] = {&reg_def_r5, nullptr};
RegisterDef const *const reg_cnt_defs_w5[] = {&reg_def_r5, nullptr};
RegisterDef const *const reg_inv_defs_w6[] = {&reg_def_r6, nullptr};
RegisterDef const *const reg_cnt_defs_w6[] = {&reg_def_r6, nullptr};
RegisterDef const *const reg_inv_defs_w7[] = {&reg_def_r7, nullptr};
RegisterDef const *const reg_cnt_defs_w7[] = {&reg_def_r7, nullptr};
RegisterDef const *const reg_inv_defs_w8[] = {&reg_def_r8, nullptr};
RegisterDef const *const reg_cnt_defs_w8[] = {&reg_def_r8, nullptr};
RegisterDef const *const reg_inv_defs_w9[] = {&reg_def_r9, nullptr};
RegisterDef const *const reg_cnt_defs_w9[] = {&reg_def_r9, nullptr};
RegisterDef const *const reg_inv_defs_w10[] = {&reg_def_r10, nullptr};
RegisterDef const *const reg_cnt_defs_w10[] = {&reg_def_r10, nullptr};
RegisterDef const *const reg_inv_defs_w11[] = {&reg_def_r11, nullptr};
RegisterDef const *const reg_cnt_defs_w11[] = {&reg_def_r11, nullptr};
RegisterDef const *const reg_inv_defs_w12[] = {&reg_def_r12, nullptr};
RegisterDef const *const reg_cnt_defs_w12[] = {&reg_def_r12, nullptr};
RegisterDef const *const reg_inv_defs_w13[] = {&reg_def_r13, nullptr};
RegisterDef const *const reg_cnt_defs_w13[] = {&reg_def_r13, nullptr};
RegisterDef const *const reg_inv_defs_w14[] = {&reg_def_r14, nullptr};
RegisterDef const *const reg_cnt_defs_w14[] = {&reg_def_r14, nullptr};
RegisterDef const *const reg_inv_defs_w15[] = {&reg_def_r15, nullptr};
RegisterDef const *const reg_cnt_defs_w15[] = {&reg_def_r15, nullptr};
RegisterDef const *const reg_inv_defs_w16[] = {&reg_def_r16, nullptr};
RegisterDef const *const reg_cnt_defs_w16[] = {&reg_def_r16, nullptr};
RegisterDef const *const reg_inv_defs_w17[] = {&reg_def_r17, nullptr};
RegisterDef const *const reg_cnt_defs_w17[] = {&reg_def_r17, nullptr};
RegisterDef const *const reg_inv_defs_w18[] = {&reg_def_r18, nullptr};
RegisterDef const *const reg_cnt_defs_w18[] = {&reg_def_r18, nullptr};
RegisterDef const *const reg_inv_defs_w19[] = {&reg_def_r19, nullptr};
RegisterDef const *const reg_cnt_defs_w19[] = {&reg_def_r19, nullptr};
RegisterDef const *const reg_inv_defs_w20[] = {&reg_def_r20, nullptr};
RegisterDef const *const reg_cnt_defs_w20[] = {&reg_def_r20, nullptr};
RegisterDef const *const reg_inv_defs_w21[] = {&reg_def_r21, nullptr};
RegisterDef const *const reg_cnt_defs_w21[] = {&reg_def_r21, nullptr};
RegisterDef const *const reg_inv_defs_w22[] = {&reg_def_r22, nullptr};
RegisterDef const *const reg_cnt_defs_w22[] = {&reg_def_r22, nullptr};
RegisterDef const *const reg_inv_defs_w23[] = {&reg_def_r23, nullptr};
RegisterDef const *const reg_cnt_defs_w23[] = {&reg_def_r23, nullptr};
RegisterDef const *const reg_inv_defs_w24[] = {&reg_def_r24, nullptr};
RegisterDef const *const reg_cnt_defs_w24[] = {&reg_def_r24, nullptr};
RegisterDef const *const reg_inv_defs_w25[] = {&reg_def_r25, nullptr};
RegisterDef const *const reg_cnt_defs_w25[] = {&reg_def_r25, nullptr};
RegisterDef const *const reg_inv_defs_w26[] = {&reg_def_r26, nullptr};
RegisterDef const *const reg_cnt_defs_w26[] = {&reg_def_r26, nullptr};
RegisterDef const *const reg_inv_defs_w27[] = {&reg_def_r27, nullptr};
RegisterDef const *const reg_cnt_defs_w27[] = {&reg_def_r27, nullptr};
RegisterDef const *const reg_inv_defs_w28[] = {&reg_def_r28, nullptr};
RegisterDef const *const reg_cnt_defs_w28[] = {&reg_def_r28, nullptr};
RegisterDef const *const reg_inv_defs_w29[] = {&reg_def_r29, nullptr};
RegisterDef const *const reg_cnt_defs_w29[] = {&reg_def_r29, nullptr};
RegisterDef const *const reg_inv_defs_w30[] = {&reg_def_r30, nullptr};
RegisterDef const *const reg_cnt_defs_w30[] = {&reg_def_r30, nullptr};
RegisterDef const *const reg_inv_defs_cpsr[] = {
    &reg_def_r8,  &reg_def_r9,  &reg_def_r10, &reg_def_r11,
    &reg_def_r12, &reg_def_r13, &reg_def_r14, nullptr};

//
// Register Definitions
//

RegisterDef const reg_def_r0 = {
    "r0",
    nullptr,
    "arg1",
    "arg1",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r0,
    ds2::Architecture::ARM64::reg_gdb_r0,
    ds2::Architecture::ARM64::reg_gcc_r0,
    ds2::Architecture::ARM64::reg_lldb_r0,
    0,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r0,
    nullptr};
RegisterDef const reg_def_r1 = {
    "r1",
    nullptr,
    "arg2",
    "arg2",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r1,
    ds2::Architecture::ARM64::reg_gdb_r1,
    ds2::Architecture::ARM64::reg_gcc_r1,
    ds2::Architecture::ARM64::reg_lldb_r1,
    8,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r1,
    nullptr};
RegisterDef const reg_def_r2 = {
    "r2",
    nullptr,
    "arg3",
    "arg3",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r2,
    ds2::Architecture::ARM64::reg_gdb_r2,
    ds2::Architecture::ARM64::reg_gcc_r2,
    ds2::Architecture::ARM64::reg_lldb_r2,
    16,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r2,
    nullptr};
RegisterDef const reg_def_r3 = {
    "r3",
    nullptr,
    "arg4",
    "arg4",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r3,
    ds2::Architecture::ARM64::reg_gdb_r3,
    ds2::Architecture::ARM64::reg_gcc_r3,
    ds2::Architecture::ARM64::reg_lldb_r3,
    24,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r3,
    nullptr};
RegisterDef const reg_def_r4 = {
    "r4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r4,
    ds2::Architecture::ARM64::reg_gdb_r4,
    ds2::Architecture::ARM64::reg_gcc_r4,
    ds2::Architecture::ARM64::reg_lldb_r4,
    32,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r4,
    nullptr};
RegisterDef const reg_def_r5 = {
    "r5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r5,
    ds2::Architecture::ARM64::reg_gdb_r5,
    ds2::Architecture::ARM64::reg_gcc_r5,
    ds2::Architecture::ARM64::reg_lldb_r5,
    40,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r5,
    nullptr};
RegisterDef const reg_def_r6 = {
    "r6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r6,
    ds2::Architecture::ARM64::reg_gdb_r6,
    ds2::Architecture::ARM64::reg_gcc_r6,
    ds2::Architecture::ARM64::reg_lldb_r6,
    48,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r6,
    nullptr};
RegisterDef const reg_def_r7 = {
    "r7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r7,
    ds2::Architecture::ARM64::reg_gdb_r7,
    ds2::Architecture::ARM64::reg_gcc_r7,
    ds2::Architecture::ARM64::reg_lldb_r7,
    56,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r7,
    nullptr};
RegisterDef const reg_def_r8 = {
    "r8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r8,
    ds2::Architecture::ARM64::reg_gdb_r8,
    ds2::Architecture::ARM64::reg_gcc_r8,
    ds2::Architecture::ARM64::reg_lldb_r8,
    64,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r8,
    nullptr};
RegisterDef const reg_def_r9 = {
    "r9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r9,
    ds2::Architecture::ARM64::reg_gdb_r9,
    ds2::Architecture::ARM64::reg_gcc_r9,
    ds2::Architecture::ARM64::reg_lldb_r9,
    72,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r9,
    nullptr};
RegisterDef const reg_def_r10 = {
    "r10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r10,
    ds2::Architecture::ARM64::reg_gdb_r10,
    ds2::Architecture::ARM64::reg_gcc_r10,
    ds2::Architecture::ARM64::reg_lldb_r10,
    80,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r10,
    nullptr};
RegisterDef const reg_def_r11 = {
    "r11",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r11,
    ds2::Architecture::ARM64::reg_gdb_r11,
    ds2::Architecture::ARM64::reg_gcc_r11,
    ds2::Architecture::ARM64::reg_lldb_r11,
    88,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r11,
    nullptr};
RegisterDef const reg_def_r12 = {
    "r12",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r12,
    ds2::Architecture::ARM64::reg_gdb_r12,
    ds2::Architecture::ARM64::reg_gcc_r12,
    ds2::Architecture::ARM64::reg_lldb_r12,
    96,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r12,
    nullptr};
RegisterDef const reg_def_r13 = {
    "r13",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r13,
    ds2::Architecture::ARM64::reg_gdb_r13,
    ds2::Architecture::ARM64::reg_gcc_r13,
    ds2::Architecture::ARM64::reg_lldb_r13,
    104,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r13,
    nullptr};
RegisterDef const reg_def_r14 = {
    "r14",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r14,
    ds2::Architecture::ARM64::reg_gdb_r14,
    ds2::Architecture::ARM64::reg_gcc_r14,
    ds2::Architecture::ARM64::reg_lldb_r14,
    112,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r14,
    nullptr};
RegisterDef const reg_def_r15 = {
    "r15",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r15,
    ds2::Architecture::ARM64::reg_gdb_r15,
    ds2::Architecture::ARM64::reg_gcc_r15,
    ds2::Architecture::ARM64::reg_lldb_r15,
    120,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r15,
    nullptr};
RegisterDef const reg_def_r16 = {
    "r16",
    nullptr,
    "ip0",
    "ip0",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r16,
    ds2::Architecture::ARM64::reg_gdb_r16,
    ds2::Architecture::ARM64::reg_gcc_r16,
    ds2::Architecture::ARM64::reg_lldb_r16,
    128,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r16,
    nullptr};
RegisterDef const reg_def_r17 = {
    "r17",
    nullptr,
    "ip1",
    "ip1",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r17,
    ds2::Architecture::ARM64::reg_gdb_r17,
    ds2::Architecture::ARM64::reg_gcc_r17,
    ds2::Architecture::ARM64::reg_lldb_r17,
    136,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r17,
    nullptr};
RegisterDef const reg_def_r18 = {
    "r18",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r18,
    ds2::Architecture::ARM64::reg_gdb_r18,
    ds2::Architecture::ARM64::reg_gcc_r18,
    ds2::Architecture::ARM64::reg_lldb_r18,
    144,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r18,
    nullptr};
RegisterDef const reg_def_r19 = {
    "r19",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r19,
    ds2::Architecture::ARM64::reg_gdb_r19,
    ds2::Architecture::ARM64::reg_gcc_r19,
    ds2::Architecture::ARM64::reg_lldb_r19,
    152,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r19,
    nullptr};
RegisterDef const reg_def_r20 = {
    "r20",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r20,
    ds2::Architecture::ARM64::reg_gdb_r20,
    ds2::Architecture::ARM64::reg_gcc_r20,
    ds2::Architecture::ARM64::reg_lldb_r20,
    160,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r20,
    nullptr};
RegisterDef const reg_def_r21 = {
    "r21",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r21,
    ds2::Architecture::ARM64::reg_gdb_r21,
    ds2::Architecture::ARM64::reg_gcc_r21,
    ds2::Architecture::ARM64::reg_lldb_r21,
    168,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r21,
    nullptr};
RegisterDef const reg_def_r22 = {
    "r22",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r22,
    ds2::Architecture::ARM64::reg_gdb_r22,
    ds2::Architecture::ARM64::reg_gcc_r22,
    ds2::Architecture::ARM64::reg_lldb_r22,
    176,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r22,
    nullptr};
RegisterDef const reg_def_r23 = {
    "r23",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r23,
    ds2::Architecture::ARM64::reg_gdb_r23,
    ds2::Architecture::ARM64::reg_gcc_r23,
    ds2::Architecture::ARM64::reg_lldb_r23,
    184,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r23,
    nullptr};
RegisterDef const reg_def_r24 = {
    "r24",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r24,
    ds2::Architecture::ARM64::reg_gdb_r24,
    ds2::Architecture::ARM64::reg_gcc_r24,
    ds2::Architecture::ARM64::reg_lldb_r24,
    192,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r24,
    nullptr};
RegisterDef const reg_def_r25 = {
    "r25",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r25,
    ds2::Architecture::ARM64::reg_gdb_r25,
    ds2::Architecture::ARM64::reg_gcc_r25,
    ds2::Architecture::ARM64::reg_lldb_r25,
    200,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r25,
    nullptr};
RegisterDef const reg_def_r26 = {
    "r26",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r26,
    ds2::Architecture::ARM64::reg_gdb_r26,
    ds2::Architecture::ARM64::reg_gcc_r26,
    ds2::Architecture::ARM64::reg_lldb_r26,
    208,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r26,
    nullptr};
RegisterDef const reg_def_r27 = {
    "r27",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r27,
    ds2::Architecture::ARM64::reg_gdb_r27,
    ds2::Architecture::ARM64::reg_gcc_r27,
    ds2::Architecture::ARM64::reg_lldb_r27,
    216,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r27,
    nullptr};
RegisterDef const reg_def_r28 = {
    "r28",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r28,
    ds2::Architecture::ARM64::reg_gdb_r28,
    ds2::Architecture::ARM64::reg_gcc_r28,
    ds2::Architecture::ARM64::reg_lldb_r28,
    224,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_r28,
    nullptr};
RegisterDef const reg_def_r29 = {
    "r29",
    nullptr,
    "fp",
    "fp",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r29,
    ds2::Architecture::ARM64::reg_gdb_r29,
    ds2::Architecture::ARM64::reg_gcc_r29,
    ds2::Architecture::ARM64::reg_lldb_r29,
    232,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingDataPointer, nullptr},
    0,
    reg_inv_defs_r29,
    nullptr};
RegisterDef const reg_def_r30 = {
    "r30",
    nullptr,
    "lr",
    "lr",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r30,
    ds2::Architecture::ARM64::reg_gdb_r30,
    ds2::Architecture::ARM64::reg_gcc_r30,
    ds2::Architecture::ARM64::reg_lldb_r30,
    240,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingCodePointer, nullptr},
    0,
    reg_inv_defs_r30,
    nullptr};
RegisterDef const reg_def_r31 = {
    "r31",
    nullptr,
    "sp",
    "sp",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_r31,
    ds2::Architecture::ARM64::reg_gdb_r31,
    ds2::Architecture::ARM64::reg_gcc_r31,
    ds2::Architecture::ARM64::reg_lldb_r31,
    248,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingDataPointer, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_pc = {
    "pc",
    nullptr,
    nullptr,
    "pc",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_pc,
    ds2::Architecture::ARM64::reg_gdb_pc,
    ds2::Architecture::ARM64::reg_gcc_pc,
    ds2::Architecture::ARM64::reg_lldb_pc,
    256,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingCodePointer, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_w0 = {
    "w0",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w0,
    ds2::Architecture::ARM64::reg_gdb_w0,
    ds2::Architecture::ARM64::reg_gcc_w0,
    ds2::Architecture::ARM64::reg_lldb_w0,
    272,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w0,
    reg_cnt_defs_w0};
RegisterDef const reg_def_w1 = {
    "w1",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w1,
    ds2::Architecture::ARM64::reg_gdb_w1,
    ds2::Architecture::ARM64::reg_gcc_w1,
    ds2::Architecture::ARM64::reg_lldb_w1,
    276,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w1,
    reg_cnt_defs_w1};
RegisterDef const reg_def_w2 = {
    "w2",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w2,
    ds2::Architecture::ARM64::reg_gdb_w2,
    ds2::Architecture::ARM64::reg_gcc_w2,
    ds2::Architecture::ARM64::reg_lldb_w2,
    280,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w2,
    reg_cnt_defs_w2};
RegisterDef const reg_def_w3 = {
    "w3",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w3,
    ds2::Architecture::ARM64::reg_gdb_w3,
    ds2::Architecture::ARM64::reg_gcc_w3,
    ds2::Architecture::ARM64::reg_lldb_w3,
    284,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w3,
    reg_cnt_defs_w3};
RegisterDef const reg_def_w4 = {
    "w4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w4,
    ds2::Architecture::ARM64::reg_gdb_w4,
    ds2::Architecture::ARM64::reg_gcc_w4,
    ds2::Architecture::ARM64::reg_lldb_w4,
    288,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w4,
    reg_cnt_defs_w4};
RegisterDef const reg_def_w5 = {
    "w5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w5,
    ds2::Architecture::ARM64::reg_gdb_w5,
    ds2::Architecture::ARM64::reg_gcc_w5,
    ds2::Architecture::ARM64::reg_lldb_w5,
    292,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w5,
    reg_cnt_defs_w5};
RegisterDef const reg_def_w6 = {
    "w6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w6,
    ds2::Architecture::ARM64::reg_gdb_w6,
    ds2::Architecture::ARM64::reg_gcc_w6,
    ds2::Architecture::ARM64::reg_lldb_w6,
    296,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w6,
    reg_cnt_defs_w6};
RegisterDef const reg_def_w7 = {
    "w7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w7,
    ds2::Architecture::ARM64::reg_gdb_w7,
    ds2::Architecture::ARM64::reg_gcc_w7,
    ds2::Architecture::ARM64::reg_lldb_w7,
    300,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w7,
    reg_cnt_defs_w7};
RegisterDef const reg_def_w8 = {
    "w8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w8,
    ds2::Architecture::ARM64::reg_gdb_w8,
    ds2::Architecture::ARM64::reg_gcc_w8,
    ds2::Architecture::ARM64::reg_lldb_w8,
    304,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w8,
    reg_cnt_defs_w8};
RegisterDef const reg_def_w9 = {
    "w9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w9,
    ds2::Architecture::ARM64::reg_gdb_w9,
    ds2::Architecture::ARM64::reg_gcc_w9,
    ds2::Architecture::ARM64::reg_lldb_w9,
    308,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w9,
    reg_cnt_defs_w9};
RegisterDef const reg_def_w10 = {
    "w10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w10,
    ds2::Architecture::ARM64::reg_gdb_w10,
    ds2::Architecture::ARM64::reg_gcc_w10,
    ds2::Architecture::ARM64::reg_lldb_w10,
    312,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w10,
    reg_cnt_defs_w10};
RegisterDef const reg_def_w11 = {
    "w11",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w11,
    ds2::Architecture::ARM64::reg_gdb_w11,
    ds2::Architecture::ARM64::reg_gcc_w11,
    ds2::Architecture::ARM64::reg_lldb_w11,
    316,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w11,
    reg_cnt_defs_w11};
RegisterDef const reg_def_w12 = {
    "w12",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w12,
    ds2::Architecture::ARM64::reg_gdb_w12,
    ds2::Architecture::ARM64::reg_gcc_w12,
    ds2::Architecture::ARM64::reg_lldb_w12,
    320,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w12,
    reg_cnt_defs_w12};
RegisterDef const reg_def_w13 = {
    "w13",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w13,
    ds2::Architecture::ARM64::reg_gdb_w13,
    ds2::Architecture::ARM64::reg_gcc_w13,
    ds2::Architecture::ARM64::reg_lldb_w13,
    324,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w13,
    reg_cnt_defs_w13};
RegisterDef const reg_def_w14 = {
    "w14",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w14,
    ds2::Architecture::ARM64::reg_gdb_w14,
    ds2::Architecture::ARM64::reg_gcc_w14,
    ds2::Architecture::ARM64::reg_lldb_w14,
    328,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w14,
    reg_cnt_defs_w14};
RegisterDef const reg_def_w15 = {
    "w15",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w15,
    ds2::Architecture::ARM64::reg_gdb_w15,
    ds2::Architecture::ARM64::reg_gcc_w15,
    ds2::Architecture::ARM64::reg_lldb_w15,
    332,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w15,
    reg_cnt_defs_w15};
RegisterDef const reg_def_w16 = {
    "w16",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w16,
    ds2::Architecture::ARM64::reg_gdb_w16,
    ds2::Architecture::ARM64::reg_gcc_w16,
    ds2::Architecture::ARM64::reg_lldb_w16,
    336,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w16,
    reg_cnt_defs_w16};
RegisterDef const reg_def_w17 = {
    "w17",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w17,
    ds2::Architecture::ARM64::reg_gdb_w17,
    ds2::Architecture::ARM64::reg_gcc_w17,
    ds2::Architecture::ARM64::reg_lldb_w17,
    340,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w17,
    reg_cnt_defs_w17};
RegisterDef const reg_def_w18 = {
    "w18",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w18,
    ds2::Architecture::ARM64::reg_gdb_w18,
    ds2::Architecture::ARM64::reg_gcc_w18,
    ds2::Architecture::ARM64::reg_lldb_w18,
    344,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w18,
    reg_cnt_defs_w18};
RegisterDef const reg_def_w19 = {
    "w19",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w19,
    ds2::Architecture::ARM64::reg_gdb_w19,
    ds2::Architecture::ARM64::reg_gcc_w19,
    ds2::Architecture::ARM64::reg_lldb_w19,
    348,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w19,
    reg_cnt_defs_w19};
RegisterDef const reg_def_w20 = {
    "w20",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w20,
    ds2::Architecture::ARM64::reg_gdb_w20,
    ds2::Architecture::ARM64::reg_gcc_w20,
    ds2::Architecture::ARM64::reg_lldb_w20,
    352,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w20,
    reg_cnt_defs_w20};
RegisterDef const reg_def_w21 = {
    "w21",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w21,
    ds2::Architecture::ARM64::reg_gdb_w21,
    ds2::Architecture::ARM64::reg_gcc_w21,
    ds2::Architecture::ARM64::reg_lldb_w21,
    356,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w21,
    reg_cnt_defs_w21};
RegisterDef const reg_def_w22 = {
    "w22",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w22,
    ds2::Architecture::ARM64::reg_gdb_w22,
    ds2::Architecture::ARM64::reg_gcc_w22,
    ds2::Architecture::ARM64::reg_lldb_w22,
    360,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w22,
    reg_cnt_defs_w22};
RegisterDef const reg_def_w23 = {
    "w23",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w23,
    ds2::Architecture::ARM64::reg_gdb_w23,
    ds2::Architecture::ARM64::reg_gcc_w23,
    ds2::Architecture::ARM64::reg_lldb_w23,
    364,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w23,
    reg_cnt_defs_w23};
RegisterDef const reg_def_w24 = {
    "w24",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w24,
    ds2::Architecture::ARM64::reg_gdb_w24,
    ds2::Architecture::ARM64::reg_gcc_w24,
    ds2::Architecture::ARM64::reg_lldb_w24,
    368,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w24,
    reg_cnt_defs_w24};
RegisterDef const reg_def_w25 = {
    "w25",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w25,
    ds2::Architecture::ARM64::reg_gdb_w25,
    ds2::Architecture::ARM64::reg_gcc_w25,
    ds2::Architecture::ARM64::reg_lldb_w25,
    372,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w25,
    reg_cnt_defs_w25};
RegisterDef const reg_def_w26 = {
    "w26",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w26,
    ds2::Architecture::ARM64::reg_gdb_w26,
    ds2::Architecture::ARM64::reg_gcc_w26,
    ds2::Architecture::ARM64::reg_lldb_w26,
    376,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w26,
    reg_cnt_defs_w26};
RegisterDef const reg_def_w27 = {
    "w27",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w27,
    ds2::Architecture::ARM64::reg_gdb_w27,
    ds2::Architecture::ARM64::reg_gcc_w27,
    ds2::Architecture::ARM64::reg_lldb_w27,
    380,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w27,
    reg_cnt_defs_w27};
RegisterDef const reg_def_w28 = {
    "w28",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w28,
    ds2::Architecture::ARM64::reg_gdb_w28,
    ds2::Architecture::ARM64::reg_gcc_w28,
    ds2::Architecture::ARM64::reg_lldb_w28,
    384,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w28,
    reg_cnt_defs_w28};
RegisterDef const reg_def_w29 = {
    "w29",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w29,
    ds2::Architecture::ARM64::reg_gdb_w29,
    ds2::Architecture::ARM64::reg_gcc_w29,
    ds2::Architecture::ARM64::reg_lldb_w29,
    388,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w29,
    reg_cnt_defs_w29};
RegisterDef const reg_def_w30 = {
    "w30",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w30,
    ds2::Architecture::ARM64::reg_gdb_w30,
    ds2::Architecture::ARM64::reg_gcc_w30,
    ds2::Architecture::ARM64::reg_lldb_w30,
    392,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w30,
    reg_cnt_defs_w30};
RegisterDef const reg_def_cpsr = {
    "cpsr",
    nullptr,
    "flags",
    "flags",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_cpsr,
    ds2::Architecture::ARM64::reg_gdb_cpsr,
    ds2::Architecture::ARM64::reg_gcc_cpsr,
    ds2::Architecture::ARM64::reg_lldb_cpsr,
    264,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingInteger, nullptr},
    0,
    reg_inv_defs_cpsr,
    nullptr};
}

//
// Public Definitions
//
namespace ds2 {
namespace Architecture {
namespace ARM64 {

LLDBDescriptor const LLDB = {1, lldb_reg_sets};
GDBDescriptor const GDB = {"aarch64", "GNU/Linux", 1, gdb_features};
}
}
}
