// !!! WARNING !!! THIS FILE WAS AUTOGENERATED !!! DO NOT MODIFY !!!
// !!! WARNING !!! MODIFY INSTEAD: Definitions/ARM64.json

#include "DebugServer2/Architecture/ARM64/RegistersDescriptors.h"

using ds2::Architecture::FlagDef;
using ds2::Architecture::FlagSet;
using ds2::Architecture::GDBFeature;
using ds2::Architecture::GDBFeatureEntry;
using ds2::Architecture::GDBVectorDef;
using ds2::Architecture::GDBVectorUnion;
using ds2::Architecture::GDBVectorUnionField;
using ds2::Architecture::LLDBRegisterSet;
using ds2::Architecture::RegisterDef;

#if defined(ENDIAN_BIG)
#define REG_REL_OFFSET(MAXBYTES, RELOFF, REGSIZE) ((MAXBYTES) - ((RELOFF) + (REGSIZE))
#else
#define REG_REL_OFFSET(MAXBYTES, RELOFF, REGSIZE) (RELOFF)
#endif

namespace {

//
// Register Definitions (Forward Declarations)
//

// Register Set (cpsr)
extern RegisterDef const reg_def_cpsr;

// Register Set (gpr)
extern RegisterDef const reg_def_x0;
extern RegisterDef const reg_def_x1;
extern RegisterDef const reg_def_x2;
extern RegisterDef const reg_def_x3;
extern RegisterDef const reg_def_x4;
extern RegisterDef const reg_def_x5;
extern RegisterDef const reg_def_x6;
extern RegisterDef const reg_def_x7;
extern RegisterDef const reg_def_x8;
extern RegisterDef const reg_def_x9;
extern RegisterDef const reg_def_x10;
extern RegisterDef const reg_def_x11;
extern RegisterDef const reg_def_x12;
extern RegisterDef const reg_def_x13;
extern RegisterDef const reg_def_x14;
extern RegisterDef const reg_def_x15;
extern RegisterDef const reg_def_x16;
extern RegisterDef const reg_def_x17;
extern RegisterDef const reg_def_x18;
extern RegisterDef const reg_def_x19;
extern RegisterDef const reg_def_x20;
extern RegisterDef const reg_def_x21;
extern RegisterDef const reg_def_x22;
extern RegisterDef const reg_def_x23;
extern RegisterDef const reg_def_x24;
extern RegisterDef const reg_def_x25;
extern RegisterDef const reg_def_x26;
extern RegisterDef const reg_def_x27;
extern RegisterDef const reg_def_x28;
extern RegisterDef const reg_def_x29;
extern RegisterDef const reg_def_x30;
extern RegisterDef const reg_def_sp;
extern RegisterDef const reg_def_pc;

// Register Set (pseudo-gpr32)
extern RegisterDef const reg_def_w0;
extern RegisterDef const reg_def_w1;
extern RegisterDef const reg_def_w2;
extern RegisterDef const reg_def_w3;
extern RegisterDef const reg_def_w4;
extern RegisterDef const reg_def_w5;
extern RegisterDef const reg_def_w6;
extern RegisterDef const reg_def_w7;
extern RegisterDef const reg_def_w8;
extern RegisterDef const reg_def_w9;
extern RegisterDef const reg_def_w10;
extern RegisterDef const reg_def_w11;
extern RegisterDef const reg_def_w12;
extern RegisterDef const reg_def_w13;
extern RegisterDef const reg_def_w14;
extern RegisterDef const reg_def_w15;
extern RegisterDef const reg_def_w16;
extern RegisterDef const reg_def_w17;
extern RegisterDef const reg_def_w18;
extern RegisterDef const reg_def_w19;
extern RegisterDef const reg_def_w20;
extern RegisterDef const reg_def_w21;
extern RegisterDef const reg_def_w22;
extern RegisterDef const reg_def_w23;
extern RegisterDef const reg_def_w24;
extern RegisterDef const reg_def_w25;
extern RegisterDef const reg_def_w26;
extern RegisterDef const reg_def_w27;
extern RegisterDef const reg_def_w28;
extern RegisterDef const reg_def_w29;
extern RegisterDef const reg_def_w30;

//
// LLDB Register Sets
//

// LLDB Register Set (General Purpose Registers)

RegisterDef const *const lldb_reg_defs_0[] = {
    &reg_def_x0,  &reg_def_x1,  &reg_def_x2,  &reg_def_x3,   &reg_def_x4,
    &reg_def_x5,  &reg_def_x6,  &reg_def_x7,  &reg_def_x8,   &reg_def_x9,
    &reg_def_x10, &reg_def_x11, &reg_def_x12, &reg_def_x13,  &reg_def_x14,
    &reg_def_x15, &reg_def_x16, &reg_def_x17, &reg_def_x18,  &reg_def_x19,
    &reg_def_x20, &reg_def_x21, &reg_def_x22, &reg_def_x23,  &reg_def_x24,
    &reg_def_x25, &reg_def_x26, &reg_def_x27, &reg_def_x28,  &reg_def_x29,
    &reg_def_x30, &reg_def_sp,  &reg_def_pc,  &reg_def_cpsr, &reg_def_w0,
    &reg_def_w1,  &reg_def_w2,  &reg_def_w3,  &reg_def_w4,   &reg_def_w5,
    &reg_def_w6,  &reg_def_w7,  &reg_def_w8,  &reg_def_w9,   &reg_def_w10,
    &reg_def_w11, &reg_def_w12, &reg_def_w13, &reg_def_w14,  &reg_def_w15,
    &reg_def_w16, &reg_def_w17, &reg_def_w18, &reg_def_w19,  &reg_def_w20,
    &reg_def_w21, &reg_def_w22, &reg_def_w23, &reg_def_w24,  &reg_def_w25,
    &reg_def_w26, &reg_def_w27, &reg_def_w28, &reg_def_w29,  &reg_def_w30,
    nullptr};

LLDBRegisterSet const lldb_reg_set_0 = {"General Purpose Registers", 65,
                                        lldb_reg_defs_0};

LLDBRegisterSet const *const lldb_reg_sets[] = {&lldb_reg_set_0, nullptr};

//
// GDB Features
//

// GDB Feature (org.gnu.gdb.aarch64.core)
GDBFeatureEntry const gdb_fents_org_gnu_gdb_aarch64_core[] = {
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x0},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x1},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x2},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x3},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x4},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x5},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x6},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x7},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x8},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x9},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x10},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x11},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x12},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x13},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x14},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x15},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x16},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x17},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x18},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x19},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x20},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x21},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x22},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x23},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x24},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x25},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x26},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x27},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x28},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x29},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_x30},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_sp},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_pc},
    {ds2::Architecture::kGDBFeatureTypeRegister, &reg_def_cpsr},
    {ds2::Architecture::kGDBFeatureTypeNone, nullptr}};
GDBFeature const gdb_feat_org_gnu_gdb_aarch64_core = {
    "org.gnu.gdb.aarch64.core", "aarch64-core.xml", 34,
    gdb_fents_org_gnu_gdb_aarch64_core};

// GDB Features (all)
GDBFeature const *const gdb_features[] = {&gdb_feat_org_gnu_gdb_aarch64_core,
                                          nullptr};

//
// LLDB Register Invalidation/Container Sets
//

RegisterDef const *const reg_inv_defs_x0[] = {&reg_def_w0, nullptr};
RegisterDef const *const reg_inv_defs_x1[] = {&reg_def_w1, nullptr};
RegisterDef const *const reg_inv_defs_x2[] = {&reg_def_w2, nullptr};
RegisterDef const *const reg_inv_defs_x3[] = {&reg_def_w3, nullptr};
RegisterDef const *const reg_inv_defs_x4[] = {&reg_def_w4, nullptr};
RegisterDef const *const reg_inv_defs_x5[] = {&reg_def_w5, nullptr};
RegisterDef const *const reg_inv_defs_x6[] = {&reg_def_w6, nullptr};
RegisterDef const *const reg_inv_defs_x7[] = {&reg_def_w7, nullptr};
RegisterDef const *const reg_inv_defs_x8[] = {&reg_def_w8, nullptr};
RegisterDef const *const reg_inv_defs_x9[] = {&reg_def_w9, nullptr};
RegisterDef const *const reg_inv_defs_x10[] = {&reg_def_w10, nullptr};
RegisterDef const *const reg_inv_defs_x11[] = {&reg_def_w11, nullptr};
RegisterDef const *const reg_inv_defs_x12[] = {&reg_def_w12, nullptr};
RegisterDef const *const reg_inv_defs_x13[] = {&reg_def_w13, nullptr};
RegisterDef const *const reg_inv_defs_x14[] = {&reg_def_w14, nullptr};
RegisterDef const *const reg_inv_defs_x15[] = {&reg_def_w15, nullptr};
RegisterDef const *const reg_inv_defs_x16[] = {&reg_def_w16, nullptr};
RegisterDef const *const reg_inv_defs_x17[] = {&reg_def_w17, nullptr};
RegisterDef const *const reg_inv_defs_x18[] = {&reg_def_w18, nullptr};
RegisterDef const *const reg_inv_defs_x19[] = {&reg_def_w19, nullptr};
RegisterDef const *const reg_inv_defs_x20[] = {&reg_def_w20, nullptr};
RegisterDef const *const reg_inv_defs_x21[] = {&reg_def_w21, nullptr};
RegisterDef const *const reg_inv_defs_x22[] = {&reg_def_w22, nullptr};
RegisterDef const *const reg_inv_defs_x23[] = {&reg_def_w23, nullptr};
RegisterDef const *const reg_inv_defs_x24[] = {&reg_def_w24, nullptr};
RegisterDef const *const reg_inv_defs_x25[] = {&reg_def_w25, nullptr};
RegisterDef const *const reg_inv_defs_x26[] = {&reg_def_w26, nullptr};
RegisterDef const *const reg_inv_defs_x27[] = {&reg_def_w27, nullptr};
RegisterDef const *const reg_inv_defs_x28[] = {&reg_def_w28, nullptr};
RegisterDef const *const reg_inv_defs_x29[] = {&reg_def_w29, nullptr};
RegisterDef const *const reg_inv_defs_x30[] = {&reg_def_w30, nullptr};
RegisterDef const *const reg_inv_defs_w0[] = {&reg_def_x0, nullptr};
RegisterDef const *const reg_cnt_defs_w0[] = {&reg_def_x0, nullptr};
RegisterDef const *const reg_inv_defs_w1[] = {&reg_def_x1, nullptr};
RegisterDef const *const reg_cnt_defs_w1[] = {&reg_def_x1, nullptr};
RegisterDef const *const reg_inv_defs_w2[] = {&reg_def_x2, nullptr};
RegisterDef const *const reg_cnt_defs_w2[] = {&reg_def_x2, nullptr};
RegisterDef const *const reg_inv_defs_w3[] = {&reg_def_x3, nullptr};
RegisterDef const *const reg_cnt_defs_w3[] = {&reg_def_x3, nullptr};
RegisterDef const *const reg_inv_defs_w4[] = {&reg_def_x4, nullptr};
RegisterDef const *const reg_cnt_defs_w4[] = {&reg_def_x4, nullptr};
RegisterDef const *const reg_inv_defs_w5[] = {&reg_def_x5, nullptr};
RegisterDef const *const reg_cnt_defs_w5[] = {&reg_def_x5, nullptr};
RegisterDef const *const reg_inv_defs_w6[] = {&reg_def_x6, nullptr};
RegisterDef const *const reg_cnt_defs_w6[] = {&reg_def_x6, nullptr};
RegisterDef const *const reg_inv_defs_w7[] = {&reg_def_x7, nullptr};
RegisterDef const *const reg_cnt_defs_w7[] = {&reg_def_x7, nullptr};
RegisterDef const *const reg_inv_defs_w8[] = {&reg_def_x8, nullptr};
RegisterDef const *const reg_cnt_defs_w8[] = {&reg_def_x8, nullptr};
RegisterDef const *const reg_inv_defs_w9[] = {&reg_def_x9, nullptr};
RegisterDef const *const reg_cnt_defs_w9[] = {&reg_def_x9, nullptr};
RegisterDef const *const reg_inv_defs_w10[] = {&reg_def_x10, nullptr};
RegisterDef const *const reg_cnt_defs_w10[] = {&reg_def_x10, nullptr};
RegisterDef const *const reg_inv_defs_w11[] = {&reg_def_x11, nullptr};
RegisterDef const *const reg_cnt_defs_w11[] = {&reg_def_x11, nullptr};
RegisterDef const *const reg_inv_defs_w12[] = {&reg_def_x12, nullptr};
RegisterDef const *const reg_cnt_defs_w12[] = {&reg_def_x12, nullptr};
RegisterDef const *const reg_inv_defs_w13[] = {&reg_def_x13, nullptr};
RegisterDef const *const reg_cnt_defs_w13[] = {&reg_def_x13, nullptr};
RegisterDef const *const reg_inv_defs_w14[] = {&reg_def_x14, nullptr};
RegisterDef const *const reg_cnt_defs_w14[] = {&reg_def_x14, nullptr};
RegisterDef const *const reg_inv_defs_w15[] = {&reg_def_x15, nullptr};
RegisterDef const *const reg_cnt_defs_w15[] = {&reg_def_x15, nullptr};
RegisterDef const *const reg_inv_defs_w16[] = {&reg_def_x16, nullptr};
RegisterDef const *const reg_cnt_defs_w16[] = {&reg_def_x16, nullptr};
RegisterDef const *const reg_inv_defs_w17[] = {&reg_def_x17, nullptr};
RegisterDef const *const reg_cnt_defs_w17[] = {&reg_def_x17, nullptr};
RegisterDef const *const reg_inv_defs_w18[] = {&reg_def_x18, nullptr};
RegisterDef const *const reg_cnt_defs_w18[] = {&reg_def_x18, nullptr};
RegisterDef const *const reg_inv_defs_w19[] = {&reg_def_x19, nullptr};
RegisterDef const *const reg_cnt_defs_w19[] = {&reg_def_x19, nullptr};
RegisterDef const *const reg_inv_defs_w20[] = {&reg_def_x20, nullptr};
RegisterDef const *const reg_cnt_defs_w20[] = {&reg_def_x20, nullptr};
RegisterDef const *const reg_inv_defs_w21[] = {&reg_def_x21, nullptr};
RegisterDef const *const reg_cnt_defs_w21[] = {&reg_def_x21, nullptr};
RegisterDef const *const reg_inv_defs_w22[] = {&reg_def_x22, nullptr};
RegisterDef const *const reg_cnt_defs_w22[] = {&reg_def_x22, nullptr};
RegisterDef const *const reg_inv_defs_w23[] = {&reg_def_x23, nullptr};
RegisterDef const *const reg_cnt_defs_w23[] = {&reg_def_x23, nullptr};
RegisterDef const *const reg_inv_defs_w24[] = {&reg_def_x24, nullptr};
RegisterDef const *const reg_cnt_defs_w24[] = {&reg_def_x24, nullptr};
RegisterDef const *const reg_inv_defs_w25[] = {&reg_def_x25, nullptr};
RegisterDef const *const reg_cnt_defs_w25[] = {&reg_def_x25, nullptr};
RegisterDef const *const reg_inv_defs_w26[] = {&reg_def_x26, nullptr};
RegisterDef const *const reg_cnt_defs_w26[] = {&reg_def_x26, nullptr};
RegisterDef const *const reg_inv_defs_w27[] = {&reg_def_x27, nullptr};
RegisterDef const *const reg_cnt_defs_w27[] = {&reg_def_x27, nullptr};
RegisterDef const *const reg_inv_defs_w28[] = {&reg_def_x28, nullptr};
RegisterDef const *const reg_cnt_defs_w28[] = {&reg_def_x28, nullptr};
RegisterDef const *const reg_inv_defs_w29[] = {&reg_def_x29, nullptr};
RegisterDef const *const reg_cnt_defs_w29[] = {&reg_def_x29, nullptr};
RegisterDef const *const reg_inv_defs_w30[] = {&reg_def_x30, nullptr};
RegisterDef const *const reg_cnt_defs_w30[] = {&reg_def_x30, nullptr};
RegisterDef const *const reg_inv_defs_cpsr[] = {
    &reg_def_x8,  &reg_def_x9,  &reg_def_x10, &reg_def_x11,
    &reg_def_x12, &reg_def_x13, &reg_def_x14, nullptr};

//
// Register Definitions
//

RegisterDef const reg_def_x0 = {
    "x0",
    nullptr,
    "arg1",
    "arg1",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x0,
    ds2::Architecture::ARM64::reg_gdb_x0,
    ds2::Architecture::ARM64::reg_ehframe_x0,
    ds2::Architecture::ARM64::reg_lldb_x0,
    0,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x0,
    nullptr};
RegisterDef const reg_def_x1 = {
    "x1",
    nullptr,
    "arg2",
    "arg2",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x1,
    ds2::Architecture::ARM64::reg_gdb_x1,
    ds2::Architecture::ARM64::reg_ehframe_x1,
    ds2::Architecture::ARM64::reg_lldb_x1,
    8,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x1,
    nullptr};
RegisterDef const reg_def_x2 = {
    "x2",
    nullptr,
    "arg3",
    "arg3",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x2,
    ds2::Architecture::ARM64::reg_gdb_x2,
    ds2::Architecture::ARM64::reg_ehframe_x2,
    ds2::Architecture::ARM64::reg_lldb_x2,
    16,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x2,
    nullptr};
RegisterDef const reg_def_x3 = {
    "x3",
    nullptr,
    "arg4",
    "arg4",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x3,
    ds2::Architecture::ARM64::reg_gdb_x3,
    ds2::Architecture::ARM64::reg_ehframe_x3,
    ds2::Architecture::ARM64::reg_lldb_x3,
    24,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x3,
    nullptr};
RegisterDef const reg_def_x4 = {
    "x4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x4,
    ds2::Architecture::ARM64::reg_gdb_x4,
    ds2::Architecture::ARM64::reg_ehframe_x4,
    ds2::Architecture::ARM64::reg_lldb_x4,
    32,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x4,
    nullptr};
RegisterDef const reg_def_x5 = {
    "x5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x5,
    ds2::Architecture::ARM64::reg_gdb_x5,
    ds2::Architecture::ARM64::reg_ehframe_x5,
    ds2::Architecture::ARM64::reg_lldb_x5,
    40,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x5,
    nullptr};
RegisterDef const reg_def_x6 = {
    "x6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x6,
    ds2::Architecture::ARM64::reg_gdb_x6,
    ds2::Architecture::ARM64::reg_ehframe_x6,
    ds2::Architecture::ARM64::reg_lldb_x6,
    48,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x6,
    nullptr};
RegisterDef const reg_def_x7 = {
    "x7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x7,
    ds2::Architecture::ARM64::reg_gdb_x7,
    ds2::Architecture::ARM64::reg_ehframe_x7,
    ds2::Architecture::ARM64::reg_lldb_x7,
    56,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x7,
    nullptr};
RegisterDef const reg_def_x8 = {
    "x8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x8,
    ds2::Architecture::ARM64::reg_gdb_x8,
    ds2::Architecture::ARM64::reg_ehframe_x8,
    ds2::Architecture::ARM64::reg_lldb_x8,
    64,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x8,
    nullptr};
RegisterDef const reg_def_x9 = {
    "x9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x9,
    ds2::Architecture::ARM64::reg_gdb_x9,
    ds2::Architecture::ARM64::reg_ehframe_x9,
    ds2::Architecture::ARM64::reg_lldb_x9,
    72,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x9,
    nullptr};
RegisterDef const reg_def_x10 = {
    "x10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x10,
    ds2::Architecture::ARM64::reg_gdb_x10,
    ds2::Architecture::ARM64::reg_ehframe_x10,
    ds2::Architecture::ARM64::reg_lldb_x10,
    80,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x10,
    nullptr};
RegisterDef const reg_def_x11 = {
    "x11",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x11,
    ds2::Architecture::ARM64::reg_gdb_x11,
    ds2::Architecture::ARM64::reg_ehframe_x11,
    ds2::Architecture::ARM64::reg_lldb_x11,
    88,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x11,
    nullptr};
RegisterDef const reg_def_x12 = {
    "x12",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x12,
    ds2::Architecture::ARM64::reg_gdb_x12,
    ds2::Architecture::ARM64::reg_ehframe_x12,
    ds2::Architecture::ARM64::reg_lldb_x12,
    96,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x12,
    nullptr};
RegisterDef const reg_def_x13 = {
    "x13",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x13,
    ds2::Architecture::ARM64::reg_gdb_x13,
    ds2::Architecture::ARM64::reg_ehframe_x13,
    ds2::Architecture::ARM64::reg_lldb_x13,
    104,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x13,
    nullptr};
RegisterDef const reg_def_x14 = {
    "x14",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x14,
    ds2::Architecture::ARM64::reg_gdb_x14,
    ds2::Architecture::ARM64::reg_ehframe_x14,
    ds2::Architecture::ARM64::reg_lldb_x14,
    112,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x14,
    nullptr};
RegisterDef const reg_def_x15 = {
    "x15",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x15,
    ds2::Architecture::ARM64::reg_gdb_x15,
    ds2::Architecture::ARM64::reg_ehframe_x15,
    ds2::Architecture::ARM64::reg_lldb_x15,
    120,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x15,
    nullptr};
RegisterDef const reg_def_x16 = {
    "x16",
    nullptr,
    "ip0",
    "ip0",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x16,
    ds2::Architecture::ARM64::reg_gdb_x16,
    ds2::Architecture::ARM64::reg_ehframe_x16,
    ds2::Architecture::ARM64::reg_lldb_x16,
    128,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x16,
    nullptr};
RegisterDef const reg_def_x17 = {
    "x17",
    nullptr,
    "ip1",
    "ip1",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x17,
    ds2::Architecture::ARM64::reg_gdb_x17,
    ds2::Architecture::ARM64::reg_ehframe_x17,
    ds2::Architecture::ARM64::reg_lldb_x17,
    136,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x17,
    nullptr};
RegisterDef const reg_def_x18 = {
    "x18",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x18,
    ds2::Architecture::ARM64::reg_gdb_x18,
    ds2::Architecture::ARM64::reg_ehframe_x18,
    ds2::Architecture::ARM64::reg_lldb_x18,
    144,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x18,
    nullptr};
RegisterDef const reg_def_x19 = {
    "x19",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x19,
    ds2::Architecture::ARM64::reg_gdb_x19,
    ds2::Architecture::ARM64::reg_ehframe_x19,
    ds2::Architecture::ARM64::reg_lldb_x19,
    152,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x19,
    nullptr};
RegisterDef const reg_def_x20 = {
    "x20",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x20,
    ds2::Architecture::ARM64::reg_gdb_x20,
    ds2::Architecture::ARM64::reg_ehframe_x20,
    ds2::Architecture::ARM64::reg_lldb_x20,
    160,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x20,
    nullptr};
RegisterDef const reg_def_x21 = {
    "x21",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x21,
    ds2::Architecture::ARM64::reg_gdb_x21,
    ds2::Architecture::ARM64::reg_ehframe_x21,
    ds2::Architecture::ARM64::reg_lldb_x21,
    168,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x21,
    nullptr};
RegisterDef const reg_def_x22 = {
    "x22",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x22,
    ds2::Architecture::ARM64::reg_gdb_x22,
    ds2::Architecture::ARM64::reg_ehframe_x22,
    ds2::Architecture::ARM64::reg_lldb_x22,
    176,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x22,
    nullptr};
RegisterDef const reg_def_x23 = {
    "x23",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x23,
    ds2::Architecture::ARM64::reg_gdb_x23,
    ds2::Architecture::ARM64::reg_ehframe_x23,
    ds2::Architecture::ARM64::reg_lldb_x23,
    184,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x23,
    nullptr};
RegisterDef const reg_def_x24 = {
    "x24",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x24,
    ds2::Architecture::ARM64::reg_gdb_x24,
    ds2::Architecture::ARM64::reg_ehframe_x24,
    ds2::Architecture::ARM64::reg_lldb_x24,
    192,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x24,
    nullptr};
RegisterDef const reg_def_x25 = {
    "x25",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x25,
    ds2::Architecture::ARM64::reg_gdb_x25,
    ds2::Architecture::ARM64::reg_ehframe_x25,
    ds2::Architecture::ARM64::reg_lldb_x25,
    200,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x25,
    nullptr};
RegisterDef const reg_def_x26 = {
    "x26",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x26,
    ds2::Architecture::ARM64::reg_gdb_x26,
    ds2::Architecture::ARM64::reg_ehframe_x26,
    ds2::Architecture::ARM64::reg_lldb_x26,
    208,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x26,
    nullptr};
RegisterDef const reg_def_x27 = {
    "x27",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x27,
    ds2::Architecture::ARM64::reg_gdb_x27,
    ds2::Architecture::ARM64::reg_ehframe_x27,
    ds2::Architecture::ARM64::reg_lldb_x27,
    216,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x27,
    nullptr};
RegisterDef const reg_def_x28 = {
    "x28",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x28,
    ds2::Architecture::ARM64::reg_gdb_x28,
    ds2::Architecture::ARM64::reg_ehframe_x28,
    ds2::Architecture::ARM64::reg_lldb_x28,
    224,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_x28,
    nullptr};
RegisterDef const reg_def_x29 = {
    "x29",
    nullptr,
    "fp",
    "fp",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x29,
    ds2::Architecture::ARM64::reg_gdb_x29,
    ds2::Architecture::ARM64::reg_ehframe_x29,
    ds2::Architecture::ARM64::reg_lldb_x29,
    232,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingDataPointer, nullptr},
    0,
    reg_inv_defs_x29,
    nullptr};
RegisterDef const reg_def_x30 = {
    "x30",
    nullptr,
    "lr",
    "lr",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_x30,
    ds2::Architecture::ARM64::reg_gdb_x30,
    ds2::Architecture::ARM64::reg_ehframe_x30,
    ds2::Architecture::ARM64::reg_lldb_x30,
    240,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingCodePointer, nullptr},
    0,
    reg_inv_defs_x30,
    nullptr};
RegisterDef const reg_def_sp = {
    "sp",
    nullptr,
    "sp",
    "sp",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_sp,
    ds2::Architecture::ARM64::reg_gdb_sp,
    ds2::Architecture::ARM64::reg_ehframe_sp,
    ds2::Architecture::ARM64::reg_lldb_sp,
    248,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingDataPointer, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_pc = {
    "pc",
    nullptr,
    nullptr,
    "pc",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_pc,
    ds2::Architecture::ARM64::reg_gdb_pc,
    ds2::Architecture::ARM64::reg_ehframe_pc,
    ds2::Architecture::ARM64::reg_lldb_pc,
    256,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingCodePointer, nullptr},
    0,
    nullptr,
    nullptr};
RegisterDef const reg_def_w0 = {
    "w0",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w0,
    ds2::Architecture::ARM64::reg_gdb_w0,
    ds2::Architecture::ARM64::reg_ehframe_w0,
    ds2::Architecture::ARM64::reg_lldb_w0,
    272,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w0,
    reg_cnt_defs_w0};
RegisterDef const reg_def_w1 = {
    "w1",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w1,
    ds2::Architecture::ARM64::reg_gdb_w1,
    ds2::Architecture::ARM64::reg_ehframe_w1,
    ds2::Architecture::ARM64::reg_lldb_w1,
    276,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w1,
    reg_cnt_defs_w1};
RegisterDef const reg_def_w2 = {
    "w2",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w2,
    ds2::Architecture::ARM64::reg_gdb_w2,
    ds2::Architecture::ARM64::reg_ehframe_w2,
    ds2::Architecture::ARM64::reg_lldb_w2,
    280,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w2,
    reg_cnt_defs_w2};
RegisterDef const reg_def_w3 = {
    "w3",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w3,
    ds2::Architecture::ARM64::reg_gdb_w3,
    ds2::Architecture::ARM64::reg_ehframe_w3,
    ds2::Architecture::ARM64::reg_lldb_w3,
    284,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w3,
    reg_cnt_defs_w3};
RegisterDef const reg_def_w4 = {
    "w4",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w4,
    ds2::Architecture::ARM64::reg_gdb_w4,
    ds2::Architecture::ARM64::reg_ehframe_w4,
    ds2::Architecture::ARM64::reg_lldb_w4,
    288,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w4,
    reg_cnt_defs_w4};
RegisterDef const reg_def_w5 = {
    "w5",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w5,
    ds2::Architecture::ARM64::reg_gdb_w5,
    ds2::Architecture::ARM64::reg_ehframe_w5,
    ds2::Architecture::ARM64::reg_lldb_w5,
    292,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w5,
    reg_cnt_defs_w5};
RegisterDef const reg_def_w6 = {
    "w6",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w6,
    ds2::Architecture::ARM64::reg_gdb_w6,
    ds2::Architecture::ARM64::reg_ehframe_w6,
    ds2::Architecture::ARM64::reg_lldb_w6,
    296,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w6,
    reg_cnt_defs_w6};
RegisterDef const reg_def_w7 = {
    "w7",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w7,
    ds2::Architecture::ARM64::reg_gdb_w7,
    ds2::Architecture::ARM64::reg_ehframe_w7,
    ds2::Architecture::ARM64::reg_lldb_w7,
    300,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w7,
    reg_cnt_defs_w7};
RegisterDef const reg_def_w8 = {
    "w8",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w8,
    ds2::Architecture::ARM64::reg_gdb_w8,
    ds2::Architecture::ARM64::reg_ehframe_w8,
    ds2::Architecture::ARM64::reg_lldb_w8,
    304,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w8,
    reg_cnt_defs_w8};
RegisterDef const reg_def_w9 = {
    "w9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w9,
    ds2::Architecture::ARM64::reg_gdb_w9,
    ds2::Architecture::ARM64::reg_ehframe_w9,
    ds2::Architecture::ARM64::reg_lldb_w9,
    308,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w9,
    reg_cnt_defs_w9};
RegisterDef const reg_def_w10 = {
    "w10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w10,
    ds2::Architecture::ARM64::reg_gdb_w10,
    ds2::Architecture::ARM64::reg_ehframe_w10,
    ds2::Architecture::ARM64::reg_lldb_w10,
    312,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w10,
    reg_cnt_defs_w10};
RegisterDef const reg_def_w11 = {
    "w11",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w11,
    ds2::Architecture::ARM64::reg_gdb_w11,
    ds2::Architecture::ARM64::reg_ehframe_w11,
    ds2::Architecture::ARM64::reg_lldb_w11,
    316,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w11,
    reg_cnt_defs_w11};
RegisterDef const reg_def_w12 = {
    "w12",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w12,
    ds2::Architecture::ARM64::reg_gdb_w12,
    ds2::Architecture::ARM64::reg_ehframe_w12,
    ds2::Architecture::ARM64::reg_lldb_w12,
    320,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w12,
    reg_cnt_defs_w12};
RegisterDef const reg_def_w13 = {
    "w13",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w13,
    ds2::Architecture::ARM64::reg_gdb_w13,
    ds2::Architecture::ARM64::reg_ehframe_w13,
    ds2::Architecture::ARM64::reg_lldb_w13,
    324,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w13,
    reg_cnt_defs_w13};
RegisterDef const reg_def_w14 = {
    "w14",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w14,
    ds2::Architecture::ARM64::reg_gdb_w14,
    ds2::Architecture::ARM64::reg_ehframe_w14,
    ds2::Architecture::ARM64::reg_lldb_w14,
    328,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w14,
    reg_cnt_defs_w14};
RegisterDef const reg_def_w15 = {
    "w15",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w15,
    ds2::Architecture::ARM64::reg_gdb_w15,
    ds2::Architecture::ARM64::reg_ehframe_w15,
    ds2::Architecture::ARM64::reg_lldb_w15,
    332,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w15,
    reg_cnt_defs_w15};
RegisterDef const reg_def_w16 = {
    "w16",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w16,
    ds2::Architecture::ARM64::reg_gdb_w16,
    ds2::Architecture::ARM64::reg_ehframe_w16,
    ds2::Architecture::ARM64::reg_lldb_w16,
    336,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w16,
    reg_cnt_defs_w16};
RegisterDef const reg_def_w17 = {
    "w17",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w17,
    ds2::Architecture::ARM64::reg_gdb_w17,
    ds2::Architecture::ARM64::reg_ehframe_w17,
    ds2::Architecture::ARM64::reg_lldb_w17,
    340,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w17,
    reg_cnt_defs_w17};
RegisterDef const reg_def_w18 = {
    "w18",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w18,
    ds2::Architecture::ARM64::reg_gdb_w18,
    ds2::Architecture::ARM64::reg_ehframe_w18,
    ds2::Architecture::ARM64::reg_lldb_w18,
    344,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w18,
    reg_cnt_defs_w18};
RegisterDef const reg_def_w19 = {
    "w19",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w19,
    ds2::Architecture::ARM64::reg_gdb_w19,
    ds2::Architecture::ARM64::reg_ehframe_w19,
    ds2::Architecture::ARM64::reg_lldb_w19,
    348,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w19,
    reg_cnt_defs_w19};
RegisterDef const reg_def_w20 = {
    "w20",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w20,
    ds2::Architecture::ARM64::reg_gdb_w20,
    ds2::Architecture::ARM64::reg_ehframe_w20,
    ds2::Architecture::ARM64::reg_lldb_w20,
    352,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w20,
    reg_cnt_defs_w20};
RegisterDef const reg_def_w21 = {
    "w21",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w21,
    ds2::Architecture::ARM64::reg_gdb_w21,
    ds2::Architecture::ARM64::reg_ehframe_w21,
    ds2::Architecture::ARM64::reg_lldb_w21,
    356,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w21,
    reg_cnt_defs_w21};
RegisterDef const reg_def_w22 = {
    "w22",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w22,
    ds2::Architecture::ARM64::reg_gdb_w22,
    ds2::Architecture::ARM64::reg_ehframe_w22,
    ds2::Architecture::ARM64::reg_lldb_w22,
    360,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w22,
    reg_cnt_defs_w22};
RegisterDef const reg_def_w23 = {
    "w23",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w23,
    ds2::Architecture::ARM64::reg_gdb_w23,
    ds2::Architecture::ARM64::reg_ehframe_w23,
    ds2::Architecture::ARM64::reg_lldb_w23,
    364,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w23,
    reg_cnt_defs_w23};
RegisterDef const reg_def_w24 = {
    "w24",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w24,
    ds2::Architecture::ARM64::reg_gdb_w24,
    ds2::Architecture::ARM64::reg_ehframe_w24,
    ds2::Architecture::ARM64::reg_lldb_w24,
    368,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w24,
    reg_cnt_defs_w24};
RegisterDef const reg_def_w25 = {
    "w25",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w25,
    ds2::Architecture::ARM64::reg_gdb_w25,
    ds2::Architecture::ARM64::reg_ehframe_w25,
    ds2::Architecture::ARM64::reg_lldb_w25,
    372,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w25,
    reg_cnt_defs_w25};
RegisterDef const reg_def_w26 = {
    "w26",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w26,
    ds2::Architecture::ARM64::reg_gdb_w26,
    ds2::Architecture::ARM64::reg_ehframe_w26,
    ds2::Architecture::ARM64::reg_lldb_w26,
    376,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w26,
    reg_cnt_defs_w26};
RegisterDef const reg_def_w27 = {
    "w27",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w27,
    ds2::Architecture::ARM64::reg_gdb_w27,
    ds2::Architecture::ARM64::reg_ehframe_w27,
    ds2::Architecture::ARM64::reg_lldb_w27,
    380,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w27,
    reg_cnt_defs_w27};
RegisterDef const reg_def_w28 = {
    "w28",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w28,
    ds2::Architecture::ARM64::reg_gdb_w28,
    ds2::Architecture::ARM64::reg_ehframe_w28,
    ds2::Architecture::ARM64::reg_lldb_w28,
    384,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w28,
    reg_cnt_defs_w28};
RegisterDef const reg_def_w29 = {
    "w29",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w29,
    ds2::Architecture::ARM64::reg_gdb_w29,
    ds2::Architecture::ARM64::reg_ehframe_w29,
    ds2::Architecture::ARM64::reg_lldb_w29,
    388,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w29,
    reg_cnt_defs_w29};
RegisterDef const reg_def_w30 = {
    "w30",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    32,
    ds2::Architecture::ARM64::reg_dwarf_w30,
    ds2::Architecture::ARM64::reg_gdb_w30,
    ds2::Architecture::ARM64::reg_ehframe_w30,
    ds2::Architecture::ARM64::reg_lldb_w30,
    392,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingSizedInteger, nullptr},
    0,
    reg_inv_defs_w30,
    reg_cnt_defs_w30};
RegisterDef const reg_def_cpsr = {
    "cpsr",
    nullptr,
    "flags",
    "flags",
    nullptr,
    64,
    ds2::Architecture::ARM64::reg_dwarf_cpsr,
    ds2::Architecture::ARM64::reg_gdb_cpsr,
    ds2::Architecture::ARM64::reg_ehframe_cpsr,
    ds2::Architecture::ARM64::reg_lldb_cpsr,
    264,
    ds2::Architecture::kLLDBVectorFormatNone,
    ds2::Architecture::kEncodingUInteger,
    ds2::Architecture::kFormatHexadecimal,
    {ds2::Architecture::kGDBEncodingInteger, nullptr},
    0,
    reg_inv_defs_cpsr,
    nullptr};

} // namespace

//
// Public Definitions
//
namespace ds2 {
namespace Architecture {
namespace ARM64 {

LLDBDescriptor const LLDB = {1, lldb_reg_sets};
GDBDescriptor const GDB = {"aarch64", "GNU/Linux", 1, gdb_features};

} // namespace ARM64
} // namespace Architecture
} // namespace ds2
